// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by generate_typescript_models.py

/**
 * Definition of an activity that can be executed.
 *
 * Attributes:
 * name: The activity function name
 * task_queue: Task queue for activity execution
 * input_schema: JSON Schema for activity input validation (must be valid JSON Schema)
 */
export interface ActivityDefinition {
    /**
     * Valid JSON Schema for activity input validation.
     */
    inputSchema: { [key: string]: any };
    /**
     * Activity function name
     */
    name: string;
    /**
     * Task queue for activity execution
     */
    taskQueue: string;
}

/**
 * Model for an individual agent streaming session.
 *
 * Attributes:
 * session_id: Unique session identifier (typically the workflow ID)
 * session_type: Type of session ('agent' or 'parent')
 */
export interface AgentSession {
    /**
     * Unique session identifier
     */
    sessionId: string;
    /**
     * Type of session
     */
    sessionType: AgentSessionType;
}

/**
 * Type of session
 *
 * Type of agent streaming session.
 */
export enum AgentSessionType {
    Agent = "agent",
    Parent = "parent",
}

/**
 * Information about an agent child workflow.
 *
 * Attributes:
 * workflow_id: Child workflow ID
 * parent_id: Parent workflow ID
 * status: Workflow execution status
 * start_time: When the workflow started
 * end_time: When the workflow ended (if completed)
 * execution_time_ms: Total execution time in milliseconds
 * agent_mode: Agent mode (ACT, PLAN, etc)
 * agent_provider: Agent provider (CLAUDE, GOOSE, etc)
 * prompt_preview: First 100 characters of the prompt
 * task_queue: Task queue used
 * run_id: Temporal run ID
 * attempt: Retry attempt number
 */
export interface AgentWorkflowInfo {
    /**
     * Agent mode (ACT, PLAN, etc)
     */
    agentMode?: null | string;
    /**
     * Agent provider (CLAUDE, GOOSE, etc)
     */
    agentProvider?: null | string;
    /**
     * Retry attempt number
     */
    attempt?: number;
    /**
     * When the workflow ended
     */
    endTime?: Date | null;
    /**
     * Total execution time in milliseconds
     */
    executionTimeMs?: number | null;
    /**
     * Parent workflow ID
     */
    parentId: string;
    /**
     * First 100 characters of the prompt
     */
    promptPreview?: null | string;
    /**
     * Temporal run ID
     */
    runId: string;
    /**
     * When the workflow started
     */
    startTime: Date;
    /**
     * Workflow execution status
     */
    status: string;
    /**
     * Task queue used
     */
    taskQueue: string;
    /**
     * Child workflow ID
     */
    workflowId: string;
}

/**
 * Detailed Information around a HITL Task.
 *
 * Attributes:
 * workflow_id: Parent workflow id
 * id: Temporal run id
 * parent_run_id: Parent workflow run id
 * title: Task title
 * description: Description of task
 * start_time: Datetime of task start
 * markdown: Task Markdown
 * input_schema: Task Schema
 * attachments: List of attachment file paths
 * chat_mode: Whether task uses chat mode
 * chat_history: List of chat messages
 * response_received: Whether a response has been received
 * timed_out: Whether the task has timed out
 */
export interface HITLTaskDetail {
    /**
     * List of attachment file paths
     */
    attachments?: string[];
    /**
     * List of chat messages
     */
    chatHistory?: HITLChatMessage[];
    /**
     * Whether task uses chat mode
     */
    chatMode?:   boolean;
    description: string;
    /**
     * Temporal run id
     */
    id:          string;
    inputSchema: { [key: string]: any };
    markdown:    string;
    /**
     * Parent workflow run id
     */
    parentRunId: string;
    /**
     * Whether a response has been received
     */
    responseReceived?: boolean;
    startTime:         Date;
    /**
     * Whether the task has timed out
     */
    timedOut?:  boolean;
    title:      string;
    workflowId: string;
}

/**
 * Represents a message in the chat history.
 *
 * When used as an inbound payload for the `add_system_message` signal, only
 * `message` and optional `data` need to be supplied. `timestamp` and
 * `is_human` will be normalized by the workflow (timestamp assigned, is_human
 * forced to False for system messages / True for human responses).
 */
export interface HITLChatMessage {
    data?:      { [key: string]: any } | null;
    isHuman?:   boolean | null;
    message:    string;
    timestamp?: Date | null;
    [property: string]: any;
}

/**
 * Information around a HITL Task.
 *
 * Attributes:
 * id: Unique identifier for a task
 * workflow_id: Parent workflow id
 * title: Task title
 * description: Description of task
 * start_time: Datetime of task start
 * chat_mode: Whether task uses chat mode
 * non_blocking: Whether task is non-blocking
 */
export interface HITLTaskInfo {
    /**
     * Whether task uses chat mode
     */
    chatMode?:   boolean;
    description: string;
    id:          string;
    /**
     * Whether task is non-blocking
     */
    nonBlocking?: boolean;
    startTime:    Date;
    title:        string;
    workflowId:   string;
}

/**
 * Complete health check response.
 *
 * Attributes:
 * status: The health status containing all service components
 */
export interface HealthResponse {
    status: HealthStatus;
}

/**
 * Overall health status containing all service components.
 *
 * Attributes:
 * temporal_service: Status of the Temporal server service
 * temporal_worker: Status of the Temporal worker service
 */
export interface HealthStatus {
    temporalService: ServiceStatus;
    temporalWorker:  ServiceStatus;
}

/**
 * Status of an individual service component.
 *
 * Attributes:
 * status: The status of the service ("up" or "down")
 * message: Optional message providing additional details about the status
 */
export interface ServiceStatus {
    message?: null | string;
    status:   string;
}

/**
 * Generic POST response to provide consistent returns.
 *
 * Attributes:
 * data: POST response data
 */
export interface PostResponse {
    data: string;
}

/**
 * Worker registration with storage metadata.
 *
 * Attributes:
 * stored_at: Timestamp when registration was stored
 */
export interface StoredWorkerRegistration {
    /**
     * List of available activities
     */
    activities?: ActivityDefinition[];
    /**
     * Timestamp when registration was generated
     */
    generatedAt?: Date;
    /**
     * Timestamp when registration was stored
     */
    storedAt?: Date;
    /**
     * Primary task queue for the worker
     */
    taskQueue: string;
    /**
     * Unique identifier for the worker
     */
    workerName: string;
    /**
     * Version of the worker
     */
    workerVersion: string;
    /**
     * List of available workflows
     */
    workflows?: WorkflowDefinition[];
}

/**
 * Definition of a workflow that can be executed.
 *
 * Attributes:
 * name: The workflow class name
 * task_queue: Task queue for workflow execution
 * input_schema: JSON Schema for workflow input validation (must be valid JSON Schema)
 * exposed: Whether this workflow should be publicly exposed (API and MCP)
 * description: Human-readable description for exposed workflows
 */
export interface WorkflowDefinition {
    /**
     * Human-readable description for exposed workflows
     */
    description?: null | string;
    /**
     * Whether this workflow should be publicly exposed (API and MCP)
     */
    exposed?: boolean;
    /**
     * Valid JSON Schema for workflow input validation.
     */
    inputSchema: { [key: string]: any };
    /**
     * [DEPRECATED] Use 'description' instead. Human-readable description for MCP tool
     */
    mcpDescription?: null | string;
    /**
     * [DEPRECATED] Use 'exposed' instead. Whether this workflow should be exposed as an MCP tool
     */
    mcpExposed?: boolean;
    /**
     * Workflow class name
     */
    name: string;
    /**
     * Task queue for workflow execution
     */
    taskQueue: string;
}

/**
 * Worker registration payload.
 *
 * Attributes:
 * worker_name: Unique identifier for the worker
 * worker_version: Version of the worker
 * task_queue: Primary task queue for the worker
 * generated_at: Timestamp when registration was generated
 * workflows: List of available workflows
 * activities: List of available activities
 */
export interface WorkerRegistration {
    /**
     * List of available activities
     */
    activities?: ActivityDefinition[];
    /**
     * Timestamp when registration was generated
     */
    generatedAt?: Date;
    /**
     * Primary task queue for the worker
     */
    taskQueue: string;
    /**
     * Unique identifier for the worker
     */
    workerName: string;
    /**
     * Version of the worker
     */
    workerVersion: string;
    /**
     * List of available workflows
     */
    workflows?: WorkflowDefinition[];
}

/**
 * Response for successful worker registration.
 *
 * Attributes:
 * message: Success message
 * worker_name: Name of the registered worker
 * registration_id: Unique registration identifier
 */
export interface WorkerRegistrationResponse {
    /**
     * Success message
     */
    message: string;
    /**
     * Unique registration identifier
     */
    registrationId: string;
    /**
     * Name of the registered worker
     */
    workerName: string;
}

/**
 * Summary of worker registration for discovery.
 *
 * Attributes:
 * worker_name: Unique identifier for the worker
 * worker_version: Version of the worker
 * task_queue: Primary task queue for the worker
 * last_updated: Timestamp of last registration update
 * workflows: List of available workflows
 * activities: List of available activities
 */
export interface WorkerRegistrationSummary {
    /**
     * List of available activities
     */
    activities: ActivityDefinition[];
    /**
     * Timestamp of last registration update
     */
    lastUpdated: Date;
    /**
     * Primary task queue for the worker
     */
    taskQueue: string;
    /**
     * Unique identifier for the worker
     */
    workerName: string;
    /**
     * Version of the worker
     */
    workerVersion: string;
    /**
     * List of available workflows
     */
    workflows: WorkflowDefinition[];
}

/**
 * Response model for workflow agent sessions query.
 *
 * Attributes:
 * workflow_id: The parent workflow ID that was queried
 * sessions: List of discovered agent sessions
 * count: Total number of sessions discovered
 */
export interface WorkflowAgentSessionsResponse {
    /**
     * Total number of sessions
     */
    count: number;
    /**
     * List of discovered agent sessions
     */
    sessions: AgentSession[];
    /**
     * The parent workflow ID
     */
    workflowId: string;
}

/**
 * Information about a discovered workflow.
 *
 * Attributes:
 * name: The name of the workflow
 * module: The module where the workflow is defined
 * parameters: List of parameter names with types for the workflow's run method
 * queues: List of task queues this workflow is registered to
 * description: Optional human-readable description of the workflow
 */
export interface WorkflowInfo {
    /**
     * Human-readable description of the workflow
     */
    description?: null | string;
    module:       string;
    name:         string;
    parameters:   { [key: string]: any };
    /**
     * Task queues this workflow is registered to
     */
    queues?: string[];
}

/**
 * Response containing a list of available workflows.
 *
 * Attributes:
 * workflows: List of workflow information objects
 */
export interface WorkflowListResponse {
    workflows: WorkflowInfo[];
}

/**
 * Response for workflow registry discovery.
 *
 * Attributes:
 * workers: Active worker registrations
 * total_workers: Total number of active workers
 * total_workflows: Total number of available workflows
 * total_activities: Total number of available activities
 */
export interface WorkflowRegistryResponse {
    /**
     * Total number of available activities
     */
    totalActivities: number;
    /**
     * Total number of active workers
     */
    totalWorkers: number;
    /**
     * Total number of available workflows
     */
    totalWorkflows: number;
    /**
     * Active worker registrations
     */
    workers: WorkerRegistrationSummary[];
}

/**
 * Overall workflow run data.
 *
 * Attributes:
 * type: Name of the workflow
 * id: Temporal Run id
 * workflow_id: Temporal Workflow id
 * status: Workflow status from Temporal
 * started: Timestamp for when the workflow started
 * duration: Duration for how long the workflow ran (or has been running, if it's not
 * completed or terminated)
 * monitor: Link to Temporal UI for monitoring this workflow run
 * pending_tasks_count: Count of pending child tasks (0 for non-running workflows)
 */
export interface WorkflowRun {
    duration:           string;
    id:                 string;
    monitor:            string;
    pendingTasksCount?: number;
    started:            Date;
    status:             WorkflowRunStatus;
    type:               string;
    workflowId:         string;
}

export enum WorkflowRunStatus {
    Canceled = "Canceled",
    Completed = "Completed",
    ContinuedAsNew = "Continued As New",
    Failed = "Failed",
    Running = "Running",
    Terminated = "Terminated",
    TimedOut = "Timed Out",
    Unknown = "Unknown",
    Unspecified = "Unspecified",
}

/**
 * Lists running and completed workflows.
 *
 * Attributes:
 * data: List of Workflow Runs
 */
export interface WorkflowRunListResponse {
    workflows: WorkflowRun[];
}

/**
 * POST data needed to initate a new workflow run.
 *
 * Attributes:
 * name: The name of the workflow to initiate
 * input: Input payload to initiate workflow, in json
 * task_queue: Optional task queue to use for workflow execution
 */
export interface WorkflowRunPayload {
    input: string;
    name:  string;
    /**
     * Optional task queue for workflow execution
     */
    taskQueue?: string;
}
