"""Script to generate TypeScript types from Pydantic models in specified modules.

Each module/output pair is processed independently.
"""

import importlib
import inspect
import json
import shutil
import subprocess
from collections.abc import Iterator
from contextlib import ExitStack, contextmanager
from pathlib import Path
from typing import Any

from pydantic import BaseModel, create_model

from awa.core.logger.logger import LoggerComponent, get_logger, init_logging

init_logging()
logger = get_logger(LoggerComponent.SCRIPT)

# --- Configuration ---
MODEL_SOURCES: list[tuple[str, Path]] = [
    ("awa.core.models.api", Path(__file__).parents[1] / "ui/src/types/api_models.ts"),
]
HEADER = """// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by generate_typescript_models.py

"""


def find_pydantic_models(module_name: str) -> list[type[BaseModel]]:
    """Find all Pydantic models in a module."""
    module = importlib.import_module(module_name)
    models = []
    for _, obj in inspect.getmembers(module):
        if (
            inspect.isclass(obj)
            and issubclass(obj, BaseModel)
            and obj is not BaseModel
            and obj.__module__ == module.__name__  # Only from this module, not imports
        ):
            models.append(obj)
    return models


@contextmanager
def override_extra_forbid(model: type[BaseModel]) -> Iterator[None]:
    """Temporarily override 'extra' to 'forbid' to prevent [k: string]: any in TypeScript."""
    original_extra = None
    if hasattr(model, "model_config"):
        original_extra = model.model_config.get("extra")
        if original_extra != "allow":
            model.model_config["extra"] = "forbid"
    try:
        yield
    finally:
        if original_extra is not None:
            model.model_config["extra"] = original_extra


def snake_to_camel(snake_str: str) -> str:
    """Convert snake_case to camelCase."""
    components = snake_str.split("_")
    return components[0] + "".join(word.capitalize() for word in components[1:])


def clean_schema(schema: dict[str, Any]) -> dict[str, Any]:
    """Clean up JSON schema for better TypeScript generation."""
    # Remove title from properties to avoid interface noise
    if "properties" in schema:
        for prop in schema["properties"].values():
            prop.pop("title", None)

    # Convert property names from snake_case to camelCase
    if "properties" in schema:
        new_properties = {}
        for prop_name, prop_value in schema["properties"].items():
            camel_name = snake_to_camel(prop_name)
            new_properties[camel_name] = prop_value
        schema["properties"] = new_properties

    # Handle required fields array
    if "required" in schema and isinstance(schema["required"], list):
        schema["required"] = [snake_to_camel(field) for field in schema["required"]]

    # Recursively clean nested schemas
    for key in ["definitions", "$defs", "properties"]:
        if key in schema and isinstance(schema[key], dict):
            for nested in schema[key].values():
                if isinstance(nested, dict):
                    clean_schema(nested)

    return schema


def generate_master_schema(models: list[type[BaseModel]]) -> str:
    """Generate a single schema using the Master model approach."""
    with ExitStack() as stack:
        # Apply extra=forbid override to all models
        for model in models:
            stack.enter_context(override_extra_forbid(model))

        # Create a master model with all models as fields
        fields = {model.__name__: (model, ...) for model in models}
        master_model = create_model("_Master_", **fields)

        # Generate schema
        schema = master_model.model_json_schema()

        # Clean the schema
        schema = clean_schema(schema)

        return json.dumps(schema, indent=2)


def generate_typescript(schema_json: str, output_file: Path) -> None:
    """Generate TypeScript from JSON schema."""
    pnpm_path = shutil.which("pnpm")
    if pnpm_path is None:
        raise RuntimeError("pnpm not found. Please install pnpm.")

    # Write schema to temp file
    temp_schema = output_file.parent / ".temp_schema.json"
    temp_schema.write_text(schema_json)

    # Calculate relative paths from current working directory
    # This avoids issues with quoted absolute paths in subprocess calls
    cwd = Path.cwd()
    try:
        rel_temp_schema = temp_schema.relative_to(cwd)
        rel_output_file = output_file.relative_to(cwd)
        use_relative_paths = True
    except ValueError:
        # If paths can't be made relative (e.g., on different drives on Windows),
        # fall back to absolute paths
        rel_temp_schema = temp_schema
        rel_output_file = output_file
        use_relative_paths = False
        logger.warning("Using absolute paths as relative paths could not be computed")

    # Use forward slashes even on Windows for better compatibility
    schema_path_str = str(rel_temp_schema).replace("\\", "/")
    output_path_str = str(rel_output_file).replace("\\", "/")

    try:
        # All arguments are hardcoded or derived from trusted model class names, not user input
        _ = subprocess.run(
            [
                pnpm_path,
                "exec",
                "quicktype",
                "-s",
                "schema",
                schema_path_str,
                "-o",
                output_path_str,
                "--lang",
                "ts",
                "--just-types",
            ],
            capture_output=True,
            check=True,
            cwd=str(cwd) if use_relative_paths else None,
        )

        # Clean up the output by removing the wrapper interface
        clean_output_file(output_file)

    except subprocess.CalledProcessError as e:
        logger.exception(f"quicktype failed: {e.stderr.decode()}")
        raise
    finally:
        # Clean up temp file
        if temp_schema.exists():
            temp_schema.unlink()


def clean_output_file(output_file: Path) -> None:
    """Remove the wrapper interface from quicktype output."""
    content = output_file.read_text()
    lines = content.splitlines(keepends=True)

    # Find and remove the first interface (which is the wrapper)
    start_idx = None
    end_idx = None
    brace_count = 0

    for i, line in enumerate(lines):
        if start_idx is None and line.startswith("export interface"):
            start_idx = i
            brace_count = 0

        if start_idx is not None:
            brace_count += line.count("{") - line.count("}")
            if brace_count == 0 and "{" in lines[start_idx]:
                end_idx = i
                break

    if start_idx is not None and end_idx is not None:
        # Remove the wrapper interface lines and any trailing empty line
        if end_idx + 1 < len(lines) and lines[end_idx + 1].strip() == "":
            new_lines = lines[:start_idx] + lines[end_idx + 2 :]
        else:
            new_lines = lines[:start_idx] + lines[end_idx + 1 :]
        output_file.write_text(HEADER + "".join(new_lines))
    else:
        # If no wrapper found, just add header
        output_file.write_text(HEADER + content)


def main() -> None:
    for module_name, output_file in MODEL_SOURCES:
        logger.info(f"Processing module '{module_name}' to '{output_file}'")

        models = find_pydantic_models(module_name)
        if not models:
            logger.warning(f"No Pydantic models found in module '{module_name}'")
            continue

        logger.info(f"Found {len(models)} models: {[m.__name__ for m in models]}")
        schema_json = generate_master_schema(models)

        # Generate TypeScript
        output_file.parent.mkdir(parents=True, exist_ok=True)
        generate_typescript(schema_json, output_file)

        logger.info(f"TypeScript models written to {output_file}")


if __name__ == "__main__":
    main()
