# ruff: noqa: ANN202, ARG002, S311
"""Auto-generated API tests from OpenAPI specification.

This file is automatically generated. Do not edit manually.
Regenerate using: python -m tests.api.generation.generate_api_tests

These tests run against a real API environment. Configure the target URL with:
- AWA_TEST_API_URL environment variable (e.g., export AWA_TEST_API_URL=http://localhost:8001)
- Or use the default from AWA configuration (localhost:8001)

Test Coverage:
- Happy Path: Successful requests with proper validation
- Error Handling: 404, 400, 422, 415 error scenarios
- Schema Validation: Response structure and field validation
- Performance: Response time and consistency checks (marked with @pytest.mark.performance)

To run all tests except performance tests:
    pytest -m "not performance" tests/api/

To run only performance tests:
    pytest -m "performance" tests/api/
"""

import json
import random
import time

import httpx
import pytest


class TestGeneratedAPI:
    """Auto-generated comprehensive tests for all API endpoints."""

    @classmethod
    def setup_class(cls) -> None:
        """Set up class for tests.

        This adds a short pause between test classes to avoid overwhelming the API server.
        """
        # Add slight delay between test runs to avoid overwhelming server
        # Use random delay between 0.1-0.5 seconds to prevent concurrent test instances
        # from all hitting the server at exactly the same time
        time.sleep(random.uniform(0.1, 0.5))

    def test_get_api_v1_health_happy_path(self, api_client: httpx.Client, api_health_check) -> None:
        """Test GET /api/v1/health - Happy Path."""
        try:
            response = api_client.get("/api/v1/health")

            # Assert specific expected status code
            assert response.status_code == 200, f"Expected status 200, got {response.status_code} for /api/v1/health"

            # Validate response headers
            assert "content-type" in response.headers, "Missing content-type header for /api/v1/health"
            assert response.headers["content-type"].startswith("application/json"), (
                f"Expected JSON content-type for /api/v1/health, got {response.headers.get('content-type', 'None')}"
            )

            # Basic response validation
            response_data = response.json()
            assert isinstance(response_data, (dict, list)), "Response is not dict or list for /api/v1/health"

            # Custom business logic validations
            # Health endpoint specific validations
            assert "status" in response_data
            assert "temporal_service" in response_data["status"]
            assert "temporal_worker" in response_data["status"]

            # Response time should be reasonable (under 8 seconds)
            # Increased from 5s to 8s to account for concurrent test execution
            assert response.elapsed.total_seconds() < 8.0, (
                f"Response too slow: {response.elapsed.total_seconds():.2f}s for /api/v1/health"
            )
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for /api/v1/health: {e!s}")
        except json.JSONDecodeError:
            pytest.fail(f"Invalid JSON response for /api/v1/health. Content: {response.text[:200]}...")

    def test_get_api_v1_health_schema_validation(self, api_client: httpx.Client, api_health_check) -> None:
        """Test GET /api/v1/health - Response Schema Validation."""
        try:
            response = api_client.get("/api/v1/health")

            # Ensure successful response for schema validation
            assert response.status_code in [200, 201, 204], (
                f"Expected status 200/201/204, got {response.status_code} for /api/v1/health"
            )

            if response.status_code != 204:  # No content responses don't have body
                try:
                    response_data = response.json()
                except json.JSONDecodeError as e:
                    pytest.fail(f"Invalid JSON response for /api/v1/health: {e!s}. Content: {response.text[:200]}...")

                # Validate response structure based on endpoint type
                # Health endpoint must have status structure
                assert "status" in response_data
                assert isinstance(response_data["status"], dict)
                assert "temporal_service" in response_data["status"]
                assert "temporal_worker" in response_data["status"]

                # Each service status must have required fields
                for service_status in response_data["status"].values():
                    assert isinstance(service_status, dict)
                    assert "status" in service_status
                    assert service_status["status"] in ["up", "down"]

                    # Validate no unexpected fields (if response is dict)
                    if isinstance(response_data, dict):
                        # Check for common required fields based on endpoint pattern
                        # Response should not contain null values for required fields
                        def check_no_null_required_fields(obj, path=""):
                            if isinstance(obj, dict):
                                for key, value in obj.items():
                                    current_path = f"{path}.{key}" if path else key
                                    if value is None and key in ["status", "name", "id"]:
                                        raise AssertionError(f"Required field {current_path} is null")
                                    check_no_null_required_fields(value, current_path)
                            elif isinstance(obj, list):
                                for i, item in enumerate(obj):
                                    check_no_null_required_fields(item, f"{path}[{i}]")

                        check_no_null_required_fields(response_data)
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for /api/v1/health schema validation: {e!s}")

    @pytest.mark.performance
    def test_get_api_v1_health_performance(self, api_client: httpx.Client, api_health_check) -> None:
        """Test GET /api/v1/health - Performance and Reliability."""
        import time

        # Test multiple requests for consistency
        response_times = []
        status_codes = []
        errors = []

        for i in range(3):
            try:
                start_time = time.time()
                response = api_client.get("/api/v1/health")
                end_time = time.time()

                response_times.append(end_time - start_time)
                status_codes.append(response.status_code)
            except Exception as e:  # noqa: BLE001
                errors.append(f"Request {i} failed: {e!s}")

        # If any requests failed, report the errors
        assert not errors, f"Some requests failed: {errors}"

        # All requests should return same status code (consistency)
        assert len(set(status_codes)) == 1, f"Inconsistent status codes: {status_codes}"

        # Average response time should be reasonable (under 3 seconds)
        # Increased from 2s to 3s to account for concurrent test execution
        avg_response_time = sum(response_times) / len(response_times)
        assert avg_response_time < 3.0, f"Average response time too slow: {avg_response_time:.2f}s for /api/v1/health"

        # No response should be extremely slow (under 8 seconds)
        # Increased from 5s to 8s to account for concurrent test execution
        assert max(response_times) < 8.0, f"Slowest response: {max(response_times):.2f}s for /api/v1/health"

    def test_get_api_v1_workflows_list_happy_path(self, api_client: httpx.Client, api_health_check) -> None:
        """Test GET /api/v1/workflows/list - Happy Path."""
        try:
            response = api_client.get("/api/v1/workflows/list")

            # Assert specific expected status code
            assert response.status_code == 200, (
                f"Expected status 200, got {response.status_code} for /api/v1/workflows/list"
            )

            # Validate response headers
            assert "content-type" in response.headers, "Missing content-type header for /api/v1/workflows/list"
            assert response.headers["content-type"].startswith("application/json"), (
                f"Expected JSON content-type for /api/v1/workflows/list, "
                f"got {response.headers.get('content-type', 'None')}"
            )

            # Basic response validation
            response_data = response.json()
            assert isinstance(response_data, (dict, list)), "Response is not dict or list for /api/v1/workflows/list"

            # Custom business logic validations
            # Workflow list/runs endpoint validation
            assert "workflows" in response_data
            assert isinstance(response_data["workflows"], list)

            # Response time should be reasonable (under 8 seconds)
            # Increased from 5s to 8s to account for concurrent test execution
            assert response.elapsed.total_seconds() < 8.0, (
                f"Response too slow: {response.elapsed.total_seconds():.2f}s for /api/v1/workflows/list"
            )
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for /api/v1/workflows/list: {e!s}")
        except json.JSONDecodeError:
            pytest.fail(f"Invalid JSON response for /api/v1/workflows/list. Content: {response.text[:200]}...")

    def test_get_api_v1_workflows_list_schema_validation(self, api_client: httpx.Client, api_health_check) -> None:
        """Test GET /api/v1/workflows/list - Response Schema Validation."""
        try:
            response = api_client.get("/api/v1/workflows/list")

            # Ensure successful response for schema validation
            assert response.status_code in [200, 201, 204], (
                f"Expected status 200/201/204, got {response.status_code} for /api/v1/workflows/list"
            )

            if response.status_code != 204:  # No content responses don't have body
                try:
                    response_data = response.json()
                except json.JSONDecodeError as e:
                    pytest.fail(
                        f"Invalid JSON response for /api/v1/workflows/list: {e!s}. Content: {response.text[:200]}...",
                    )

                # Validate response structure based on endpoint type
                # Workflows list must have workflows array
                assert "workflows" in response_data
                assert isinstance(response_data["workflows"], list)

                # Each workflow must have required fields
                for workflow in response_data["workflows"]:
                    assert isinstance(workflow, dict)
                    assert "name" in workflow
                    assert "module" in workflow
                    assert isinstance(workflow["name"], str)
                    assert isinstance(workflow["module"], str)

                # Validate no unexpected fields (if response is dict)
                if isinstance(response_data, dict):
                    # Check for common required fields based on endpoint pattern
                    # Response should not contain null values for required fields
                    def check_no_null_required_fields(obj, path=""):
                        if isinstance(obj, dict):
                            for key, value in obj.items():
                                current_path = f"{path}.{key}" if path else key
                                if value is None and key in ["status", "name", "id"]:
                                    raise AssertionError(f"Required field {current_path} is null")
                                check_no_null_required_fields(value, current_path)
                        elif isinstance(obj, list):
                            for i, item in enumerate(obj):
                                check_no_null_required_fields(item, f"{path}[{i}]")

                    check_no_null_required_fields(response_data)
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for /api/v1/workflows/list schema validation: {e!s}")

    @pytest.mark.performance
    def test_get_api_v1_workflows_list_performance(self, api_client: httpx.Client, api_health_check) -> None:
        """Test GET /api/v1/workflows/list - Performance and Reliability."""
        import time

        # Test multiple requests for consistency
        response_times = []
        status_codes = []
        errors = []

        for i in range(3):
            try:
                start_time = time.time()
                response = api_client.get("/api/v1/workflows/list")
                end_time = time.time()

                response_times.append(end_time - start_time)
                status_codes.append(response.status_code)
            except Exception as e:  # noqa: BLE001
                errors.append(f"Request {i} failed: {e!s}")

        # If any requests failed, report the errors
        assert not errors, f"Some requests failed: {errors}"

        # All requests should return same status code (consistency)
        assert len(set(status_codes)) == 1, f"Inconsistent status codes: {status_codes}"

        # Average response time should be reasonable (under 3 seconds)
        # Increased from 2s to 3s to account for concurrent test execution
        avg_response_time = sum(response_times) / len(response_times)
        assert avg_response_time < 3.0, (
            f"Average response time too slow: {avg_response_time:.2f}s for /api/v1/workflows/list"
        )

        # No response should be extremely slow (under 8 seconds)
        # Increased from 5s to 8s to account for concurrent test execution
        assert max(response_times) < 8.0, f"Slowest response: {max(response_times):.2f}s for /api/v1/workflows/list"

    def test_get_api_v1_workflows_runs_happy_path(self, api_client: httpx.Client, api_health_check) -> None:
        """Test GET /api/v1/workflows/runs - Happy Path."""
        try:
            response = api_client.get("/api/v1/workflows/runs")

            # Assert specific expected status code
            assert response.status_code == 200, (
                f"Expected status 200, got {response.status_code} for /api/v1/workflows/runs"
            )

            # Validate response headers
            assert "content-type" in response.headers, "Missing content-type header for /api/v1/workflows/runs"
            assert response.headers["content-type"].startswith("application/json"), (
                f"Expected JSON content-type for /api/v1/workflows/runs, "
                f"got {response.headers.get('content-type', 'None')}"
            )

            # Basic response validation
            response_data = response.json()
            assert isinstance(response_data, (dict, list)), "Response is not dict or list for /api/v1/workflows/runs"

            # Custom business logic validations
            # Workflow list/runs endpoint validation
            assert "workflows" in response_data
            assert isinstance(response_data["workflows"], list)

            # Response time should be reasonable (under 8 seconds)
            # Increased from 5s to 8s to account for concurrent test execution
            assert response.elapsed.total_seconds() < 8.0, (
                f"Response too slow: {response.elapsed.total_seconds():.2f}s for /api/v1/workflows/runs"
            )
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for /api/v1/workflows/runs: {e!s}")
        except json.JSONDecodeError:
            pytest.fail(f"Invalid JSON response for /api/v1/workflows/runs. Content: {response.text[:200]}...")

    def test_get_api_v1_workflows_runs_schema_validation(self, api_client: httpx.Client, api_health_check) -> None:
        """Test GET /api/v1/workflows/runs - Response Schema Validation."""
        try:
            response = api_client.get("/api/v1/workflows/runs")

            # Ensure successful response for schema validation
            assert response.status_code in [200, 201, 204], (
                f"Expected status 200/201/204, got {response.status_code} for /api/v1/workflows/runs"
            )

            if response.status_code != 204:  # No content responses don't have body
                try:
                    response_data = response.json()
                except json.JSONDecodeError as e:
                    pytest.fail(
                        f"Invalid JSON response for /api/v1/workflows/runs: {e!s}. Content: {response.text[:200]}...",
                    )

                # Validate response structure based on endpoint type
                # Workflow runs response validation
                if isinstance(response_data, list):
                    # List of runs
                    for run in response_data:
                        assert isinstance(run, dict)
                else:
                    # Single run or paginated response
                    assert isinstance(response_data, dict)

                    # Validate no unexpected fields (if response is dict)
                    if isinstance(response_data, dict):
                        # Check for common required fields based on endpoint pattern
                        # Response should not contain null values for required fields
                        def check_no_null_required_fields(obj, path=""):
                            if isinstance(obj, dict):
                                for key, value in obj.items():
                                    current_path = f"{path}.{key}" if path else key
                                    if value is None and key in ["status", "name", "id"]:
                                        raise AssertionError(f"Required field {current_path} is null")
                                    check_no_null_required_fields(value, current_path)
                            elif isinstance(obj, list):
                                for i, item in enumerate(obj):
                                    check_no_null_required_fields(item, f"{path}[{i}]")

                        check_no_null_required_fields(response_data)
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for /api/v1/workflows/runs schema validation: {e!s}")

    @pytest.mark.performance
    def test_get_api_v1_workflows_runs_performance(self, api_client: httpx.Client, api_health_check) -> None:
        """Test GET /api/v1/workflows/runs - Performance and Reliability."""
        import time

        # Test multiple requests for consistency
        response_times = []
        status_codes = []
        errors = []

        for i in range(3):
            try:
                start_time = time.time()
                response = api_client.get("/api/v1/workflows/runs")
                end_time = time.time()

                response_times.append(end_time - start_time)
                status_codes.append(response.status_code)
            except Exception as e:  # noqa: BLE001
                errors.append(f"Request {i} failed: {e!s}")

        # If any requests failed, report the errors
        assert not errors, f"Some requests failed: {errors}"

        # All requests should return same status code (consistency)
        assert len(set(status_codes)) == 1, f"Inconsistent status codes: {status_codes}"

        # Average response time should be reasonable (under 3 seconds)
        # Increased from 2s to 3s to account for concurrent test execution
        avg_response_time = sum(response_times) / len(response_times)
        assert avg_response_time < 3.0, (
            f"Average response time too slow: {avg_response_time:.2f}s for /api/v1/workflows/runs"
        )

        # No response should be extremely slow (under 8 seconds)
        # Increased from 5s to 8s to account for concurrent test execution
        assert max(response_times) < 8.0, f"Slowest response: {max(response_times):.2f}s for /api/v1/workflows/runs"

    def test_post_api_v1_workers_register_happy_path(self, api_client: httpx.Client, api_health_check) -> None:
        """Test POST /api/v1/workers/register - Happy Path."""
        try:
            payload = {
                "worker_name": "test-worker",
                "worker_version": "1.0.0",
                "task_queue": "default-task-queue",
                "generated_at": "2025-08-08T17:36:19.254780+00:00",
                "workflows": [
                    {
                        "name": "awa-hello-world",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "type": "string",
                                },
                            },
                            "required": [
                                "name",
                            ],
                            "title": "HelloWorldInput",
                        },
                    },
                    {
                        "name": "awa-hello-world",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "type": "string",
                                },
                            },
                            "required": [
                                "name",
                            ],
                            "title": "HelloWorldInput",
                        },
                    },
                ],
            }
            response = api_client.post("/api/v1/workers/register", json=payload)

            # Assert specific expected status code
            assert response.status_code == 201, (
                f"Expected status 201, got {response.status_code} for /api/v1/workers/register"
            )

            # Validate response headers
            assert "content-type" in response.headers, "Missing content-type header for /api/v1/workers/register"
            assert response.headers["content-type"].startswith("application/json"), (
                f"Expected JSON content-type for /api/v1/workers/register, "
                f"got {response.headers.get('content-type', 'None')}"
            )

            # Basic response validation
            response_data = response.json()
            assert isinstance(response_data, (dict, list)), "Response is not dict or list for /api/v1/workers/register"

            # Custom business logic validations

            # Response time should be reasonable (under 8 seconds)
            # Increased from 5s to 8s to account for concurrent test execution
            assert response.elapsed.total_seconds() < 8.0, (
                f"Response too slow: {response.elapsed.total_seconds():.2f}s for /api/v1/workers/register"
            )
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for /api/v1/workers/register: {e!s}")
        except json.JSONDecodeError:
            pytest.fail(f"Invalid JSON response for /api/v1/workers/register. Content: {response.text[:200]}...")

    def test_post_api_v1_workers_register_variant_1(self, api_client: httpx.Client, api_health_check) -> None:
        """Test POST /api/v1/workers/register - Minimal WorkerRegistration with required fields only."""
        try:
            payload = {
                "worker_name": "worker",
                "worker_version": "1.0",
                "task_queue": "default",
            }
            response = api_client.post("/api/v1/workers/register", json=payload)

            # Should return successful status
            assert response.status_code == 201

            # Validate response structure
            response_data = response.json()
            assert isinstance(response_data, (dict, list))
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for /api/v1/workers/register variant 1: {e!s}")
        except json.JSONDecodeError:
            pytest.fail(
                f"Invalid JSON response for /api/v1/workers/register variant 1. Content: {response.text[:200]}...",
            )

    def test_post_api_v1_workers_register_variant_2(self, api_client: httpx.Client, api_health_check) -> None:
        """Test POST /api/v1/workers/register - Complete WorkerRegistration with all fields."""
        try:
            payload = {
                "worker_name": "test-worker",
                "worker_version": "1.0.0",
                "task_queue": "default-task-queue",
                "generated_at": "2025-08-08T17:36:19.255526+00:00",
                "workflows": [
                    {
                        "name": "awa-hello-world",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "type": "string",
                                },
                            },
                            "required": [
                                "name",
                            ],
                            "title": "HelloWorldInput",
                        },
                    },
                    {
                        "name": "awa-hello-world",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "type": "string",
                                },
                            },
                            "required": [
                                "name",
                            ],
                            "title": "HelloWorldInput",
                        },
                    },
                ],
                "activities": [
                    {
                        "name": "test-activity",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "input": {
                                    "type": "string",
                                    "description": "Activity input data",
                                },
                            },
                            "required": [
                                "input",
                            ],
                        },
                    },
                    {
                        "name": "test-activity",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "input": {
                                    "type": "string",
                                    "description": "Activity input data",
                                },
                            },
                            "required": [
                                "input",
                            ],
                        },
                    },
                ],
            }
            response = api_client.post("/api/v1/workers/register", json=payload)

            # Should return successful status
            assert response.status_code == 201

            # Validate response structure
            response_data = response.json()
            assert isinstance(response_data, (dict, list))
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for /api/v1/workers/register variant 2: {e!s}")
        except json.JSONDecodeError:
            pytest.fail(
                f"Invalid JSON response for /api/v1/workers/register variant 2. Content: {response.text[:200]}...",
            )

    def test_post_api_v1_workers_register_variant_3(self, api_client: httpx.Client, api_health_check) -> None:
        """Test POST /api/v1/workers/register - WorkerRegistration with edge case values."""
        try:
            payload = {
                "worker_name": "test-worker",
                "worker_version": "1.0.0",
                "task_queue": "default-task-queue",
            }
            response = api_client.post("/api/v1/workers/register", json=payload)

            # Should return successful status
            assert response.status_code == 201

            # Validate response structure
            response_data = response.json()
            assert isinstance(response_data, (dict, list))
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for /api/v1/workers/register variant 3: {e!s}")
        except json.JSONDecodeError:
            pytest.fail(
                f"Invalid JSON response for /api/v1/workers/register variant 3. Content: {response.text[:200]}...",
            )

    def test_post_api_v1_workers_register_missing_required_worker_name_field(
        self,
        api_client: httpx.Client,
        api_health_check,
    ) -> None:
        """Test POST /api/v1/workers/register - Missing required 'worker_name' field."""
        try:
            invalid_payload = {
                "worker_version": "1.0.0",
                "task_queue": "default-task-queue",
                "generated_at": "2025-08-08T17:36:19.255586+00:00",
                "workflows": [
                    {
                        "name": "awa-hello-world",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "type": "string",
                                },
                            },
                            "required": [
                                "name",
                            ],
                            "title": "HelloWorldInput",
                        },
                    },
                    {
                        "name": "awa-hello-world",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "type": "string",
                                },
                            },
                            "required": [
                                "name",
                            ],
                            "title": "HelloWorldInput",
                        },
                    },
                ],
                "activities": [
                    {
                        "name": "test-activity",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "input": {
                                    "type": "string",
                                    "description": "Activity input data",
                                },
                            },
                            "required": [
                                "input",
                            ],
                        },
                    },
                    {
                        "name": "test-activity",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "input": {
                                    "type": "string",
                                    "description": "Activity input data",
                                },
                            },
                            "required": [
                                "input",
                            ],
                        },
                    },
                ],
            }
            response = api_client.post("/api/v1/workers/register", json=invalid_payload)

            # Should return error status code (422 - Validation Error)
            assert response.status_code in [400, 422, 404], (
                f"Expected error status code, got {response.status_code} for invalid payload test"
            )

            # Should return error details in JSON format
            if response.headers.get("content-type", "").startswith("application/json"):
                try:
                    error_data = response.json()
                    assert isinstance(error_data, dict), "Error response is not a JSON object"
                except json.JSONDecodeError:
                    pytest.fail(f"Invalid JSON in error response: {response.text[:200]}...")
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for invalid payload test: {e!s}")

    def test_post_api_v1_workers_register_missing_required_worker_version_field(
        self,
        api_client: httpx.Client,
        api_health_check,
    ) -> None:
        """Test POST /api/v1/workers/register - Missing required 'worker_version' field."""
        try:
            invalid_payload = {
                "worker_name": "test-worker",
                "task_queue": "default-task-queue",
                "generated_at": "2025-08-08T17:36:19.255586+00:00",
                "workflows": [
                    {
                        "name": "awa-hello-world",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "type": "string",
                                },
                            },
                            "required": [
                                "name",
                            ],
                            "title": "HelloWorldInput",
                        },
                    },
                    {
                        "name": "awa-hello-world",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "type": "string",
                                },
                            },
                            "required": [
                                "name",
                            ],
                            "title": "HelloWorldInput",
                        },
                    },
                ],
                "activities": [
                    {
                        "name": "test-activity",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "input": {
                                    "type": "string",
                                    "description": "Activity input data",
                                },
                            },
                            "required": [
                                "input",
                            ],
                        },
                    },
                    {
                        "name": "test-activity",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "input": {
                                    "type": "string",
                                    "description": "Activity input data",
                                },
                            },
                            "required": [
                                "input",
                            ],
                        },
                    },
                ],
            }
            response = api_client.post("/api/v1/workers/register", json=invalid_payload)

            # Should return error status code (422 - Validation Error)
            assert response.status_code in [400, 422, 404], (
                f"Expected error status code, got {response.status_code} for invalid payload test"
            )

            # Should return error details in JSON format
            if response.headers.get("content-type", "").startswith("application/json"):
                try:
                    error_data = response.json()
                    assert isinstance(error_data, dict), "Error response is not a JSON object"
                except json.JSONDecodeError:
                    pytest.fail(f"Invalid JSON in error response: {response.text[:200]}...")
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for invalid payload test: {e!s}")

    def test_post_api_v1_workers_register_missing_required_task_queue_field(
        self,
        api_client: httpx.Client,
        api_health_check,
    ) -> None:
        """Test POST /api/v1/workers/register - Missing required 'task_queue' field."""
        try:
            invalid_payload = {
                "worker_name": "test-worker",
                "worker_version": "1.0.0",
                "generated_at": "2025-08-08T17:36:19.255586+00:00",
                "workflows": [
                    {
                        "name": "awa-hello-world",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "type": "string",
                                },
                            },
                            "required": [
                                "name",
                            ],
                            "title": "HelloWorldInput",
                        },
                    },
                    {
                        "name": "awa-hello-world",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "type": "string",
                                },
                            },
                            "required": [
                                "name",
                            ],
                            "title": "HelloWorldInput",
                        },
                    },
                ],
                "activities": [
                    {
                        "name": "test-activity",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "input": {
                                    "type": "string",
                                    "description": "Activity input data",
                                },
                            },
                            "required": [
                                "input",
                            ],
                        },
                    },
                    {
                        "name": "test-activity",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "input": {
                                    "type": "string",
                                    "description": "Activity input data",
                                },
                            },
                            "required": [
                                "input",
                            ],
                        },
                    },
                ],
            }
            response = api_client.post("/api/v1/workers/register", json=invalid_payload)

            # Should return error status code (422 - Validation Error)
            assert response.status_code in [400, 422, 404], (
                f"Expected error status code, got {response.status_code} for invalid payload test"
            )

            # Should return error details in JSON format
            if response.headers.get("content-type", "").startswith("application/json"):
                try:
                    error_data = response.json()
                    assert isinstance(error_data, dict), "Error response is not a JSON object"
                except json.JSONDecodeError:
                    pytest.fail(f"Invalid JSON in error response: {response.text[:200]}...")
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for invalid payload test: {e!s}")

    def test_post_api_v1_workers_register_wrong_type_for_worker_name_field(
        self,
        api_client: httpx.Client,
        api_health_check,
    ) -> None:
        """Test POST /api/v1/workers/register - Wrong type for 'worker_name' field."""
        try:
            invalid_payload = {
                "worker_name": 12345,
                "worker_version": "1.0.0",
                "task_queue": "default-task-queue",
                "generated_at": "2025-08-08T17:36:19.255586+00:00",
                "workflows": [
                    {
                        "name": "awa-hello-world",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "type": "string",
                                },
                            },
                            "required": [
                                "name",
                            ],
                            "title": "HelloWorldInput",
                        },
                    },
                    {
                        "name": "awa-hello-world",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "type": "string",
                                },
                            },
                            "required": [
                                "name",
                            ],
                            "title": "HelloWorldInput",
                        },
                    },
                ],
                "activities": [
                    {
                        "name": "test-activity",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "input": {
                                    "type": "string",
                                    "description": "Activity input data",
                                },
                            },
                            "required": [
                                "input",
                            ],
                        },
                    },
                    {
                        "name": "test-activity",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "input": {
                                    "type": "string",
                                    "description": "Activity input data",
                                },
                            },
                            "required": [
                                "input",
                            ],
                        },
                    },
                ],
            }
            response = api_client.post("/api/v1/workers/register", json=invalid_payload)

            # Should return error status code (422 - Validation Error)
            assert response.status_code in [400, 422, 404], (
                f"Expected error status code, got {response.status_code} for invalid payload test"
            )

            # Should return error details in JSON format
            if response.headers.get("content-type", "").startswith("application/json"):
                try:
                    error_data = response.json()
                    assert isinstance(error_data, dict), "Error response is not a JSON object"
                except json.JSONDecodeError:
                    pytest.fail(f"Invalid JSON in error response: {response.text[:200]}...")
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for invalid payload test: {e!s}")

    def test_post_api_v1_workers_register_wrong_type_for_worker_version_field(
        self,
        api_client: httpx.Client,
        api_health_check,
    ) -> None:
        """Test POST /api/v1/workers/register - Wrong type for 'worker_version' field."""
        try:
            invalid_payload = {
                "worker_name": "test-worker",
                "worker_version": 12345,
                "task_queue": "default-task-queue",
                "generated_at": "2025-08-08T17:36:19.255586+00:00",
                "workflows": [
                    {
                        "name": "awa-hello-world",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "type": "string",
                                },
                            },
                            "required": [
                                "name",
                            ],
                            "title": "HelloWorldInput",
                        },
                    },
                    {
                        "name": "awa-hello-world",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "type": "string",
                                },
                            },
                            "required": [
                                "name",
                            ],
                            "title": "HelloWorldInput",
                        },
                    },
                ],
                "activities": [
                    {
                        "name": "test-activity",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "input": {
                                    "type": "string",
                                    "description": "Activity input data",
                                },
                            },
                            "required": [
                                "input",
                            ],
                        },
                    },
                    {
                        "name": "test-activity",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "input": {
                                    "type": "string",
                                    "description": "Activity input data",
                                },
                            },
                            "required": [
                                "input",
                            ],
                        },
                    },
                ],
            }
            response = api_client.post("/api/v1/workers/register", json=invalid_payload)

            # Should return error status code (422 - Validation Error)
            assert response.status_code in [400, 422, 404], (
                f"Expected error status code, got {response.status_code} for invalid payload test"
            )

            # Should return error details in JSON format
            if response.headers.get("content-type", "").startswith("application/json"):
                try:
                    error_data = response.json()
                    assert isinstance(error_data, dict), "Error response is not a JSON object"
                except json.JSONDecodeError:
                    pytest.fail(f"Invalid JSON in error response: {response.text[:200]}...")
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for invalid payload test: {e!s}")

    def test_post_api_v1_workers_register_malformed_json(self, api_client: httpx.Client, api_health_check) -> None:
        """Test POST /api/v1/workers/register - Malformed JSON."""
        try:
            # Send invalid JSON
            response = api_client.post(
                "/api/v1/workers/register",
                content="{invalid json",
                headers={"content-type": "application/json"},
            )

            # Should return 400 or 422 for malformed data
            assert response.status_code in [400, 422], (
                f"Expected 400 or 422 status for malformed JSON, got {response.status_code}"
            )

            # Should return error details
            if response.headers.get("content-type", "").startswith("application/json"):
                try:
                    error_data = response.json()
                    assert isinstance(error_data, dict), "Error response is not a JSON object"
                except json.JSONDecodeError:
                    pytest.fail(f"Invalid JSON in error response for malformed JSON test: {response.text[:200]}...")
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for malformed JSON test: {e!s}")

    def test_post_api_v1_workers_register_unsupported_content_type(
        self,
        api_client: httpx.Client,
        api_health_check,
    ) -> None:
        """Test POST /api/v1/workers/register - Unsupported Content Type."""
        try:
            response = api_client.post(
                "/api/v1/workers/register",
                content="test data",
                headers={"content-type": "text/plain"},
            )

            # Should return 415 Unsupported Media Type or 400 Bad Request
            assert response.status_code in [400, 415, 422], (
                f"Expected 400, 415, or 422 status for unsupported content type, got {response.status_code}"
            )

            # Optional: check for error response
            if response.headers.get("content-type", "").startswith("application/json"):
                try:
                    error_data = response.json()
                    assert isinstance(error_data, dict), "Error response is not a JSON object"
                except json.JSONDecodeError:
                    pass  # Some servers may not return JSON for content-type errors
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for unsupported content type test: {e!s}")

    def test_post_api_v1_workers_register_schema_validation(self, api_client: httpx.Client, api_health_check) -> None:
        """Test POST /api/v1/workers/register - Response Schema Validation."""
        try:
            payload = {
                "worker_name": "test-worker",
                "worker_version": "1.0.0",
                "task_queue": "default-task-queue",
                "generated_at": "2025-08-08T17:36:19.254780+00:00",
                "workflows": [
                    {
                        "name": "awa-hello-world",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "type": "string",
                                },
                            },
                            "required": [
                                "name",
                            ],
                            "title": "HelloWorldInput",
                        },
                    },
                    {
                        "name": "awa-hello-world",
                        "task_queue": "awa_default",
                        "input_schema": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Name",
                                    "type": "string",
                                },
                            },
                            "required": [
                                "name",
                            ],
                            "title": "HelloWorldInput",
                        },
                    },
                ],
            }
            response = api_client.post("/api/v1/workers/register", json=payload)

            # Ensure successful response for schema validation
            assert response.status_code in [200, 201, 204], (
                f"Expected status 200/201/204, got {response.status_code} for /api/v1/workers/register"
            )

            if response.status_code != 204:  # No content responses don't have body
                try:
                    response_data = response.json()
                except json.JSONDecodeError as e:
                    pytest.fail(
                        f"Invalid JSON response for /api/v1/workers/register: {e!s}. Content: {response.text[:200]}...",
                    )

                # Validate response structure based on endpoint type

                # Validate no unexpected fields (if response is dict)
                if isinstance(response_data, dict):
                    # Check for common required fields based on endpoint pattern
                    # Response should not contain null values for required fields
                    def check_no_null_required_fields(obj, path=""):
                        if isinstance(obj, dict):
                            for key, value in obj.items():
                                current_path = f"{path}.{key}" if path else key
                                if value is None and key in ["status", "name", "id"]:
                                    raise AssertionError(f"Required field {current_path} is null")
                                check_no_null_required_fields(value, current_path)
                        elif isinstance(obj, list):
                            for i, item in enumerate(obj):
                                check_no_null_required_fields(item, f"{path}[{i}]")

                    check_no_null_required_fields(response_data)
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for /api/v1/workers/register schema validation: {e!s}")

    def test_post_api_v1_workflows_happy_path(self, api_client: httpx.Client, api_health_check) -> None:
        """Test POST /api/v1/workflows - Happy Path."""
        try:
            payload = {
                "name": "test-worker",
                "input": '{"name": "TestUser"}',
                "task_queue": "default-task-queue",
            }
            response = api_client.post("/api/v1/workflows", json=payload)

            # Assert specific expected status code
            assert response.status_code == 200, f"Expected status 200, got {response.status_code} for /api/v1/workflows"

            # Validate response headers
            assert "content-type" in response.headers, "Missing content-type header for /api/v1/workflows"
            assert response.headers["content-type"].startswith("application/json"), (
                f"Expected JSON content-type for /api/v1/workflows, got {response.headers.get('content-type', 'None')}"
            )

            # Basic response validation
            response_data = response.json()
            assert isinstance(response_data, (dict, list)), "Response is not dict or list for /api/v1/workflows"

            # Custom business logic validations
            # Workflow creation endpoint validation
            assert "data" in response_data
            assert response_data["data"] == "success"

            # Response time should be reasonable (under 8 seconds)
            # Increased from 5s to 8s to account for concurrent test execution
            assert response.elapsed.total_seconds() < 8.0, (
                f"Response too slow: {response.elapsed.total_seconds():.2f}s for /api/v1/workflows"
            )
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for /api/v1/workflows: {e!s}")
        except json.JSONDecodeError:
            pytest.fail(f"Invalid JSON response for /api/v1/workflows. Content: {response.text[:200]}...")

    def test_post_api_v1_workflows_variant_1(self, api_client: httpx.Client, api_health_check) -> None:
        """Test POST /api/v1/workflows - Hello Human workflow with basic name."""
        try:
            payload = {
                "name": "awa-hello-human",
                "input": '{"name": "TestUser"}',
            }
            response = api_client.post("/api/v1/workflows", json=payload)

            # Should return successful status
            assert response.status_code == 200

            # Validate response structure
            response_data = response.json()
            assert isinstance(response_data, (dict, list))
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for /api/v1/workflows variant 1: {e!s}")
        except json.JSONDecodeError:
            pytest.fail(f"Invalid JSON response for /api/v1/workflows variant 1. Content: {response.text[:200]}...")

    def test_post_api_v1_workflows_variant_2(self, api_client: httpx.Client, api_health_check) -> None:
        """Test POST /api/v1/workflows - Hello Human workflow with special characters."""
        try:
            payload = {
                "name": "awa-hello-human",
                "input": '{"name": "Mar\u00eda Jos\u00e9"}',
            }
            response = api_client.post("/api/v1/workflows", json=payload)

            # Should return successful status
            assert response.status_code == 200

            # Validate response structure
            response_data = response.json()
            assert isinstance(response_data, (dict, list))
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for /api/v1/workflows variant 2: {e!s}")
        except json.JSONDecodeError:
            pytest.fail(f"Invalid JSON response for /api/v1/workflows variant 2. Content: {response.text[:200]}...")

    def test_post_api_v1_workflows_variant_3(self, api_client: httpx.Client, api_health_check) -> None:
        """Test POST /api/v1/workflows - Hello World workflow with simple input."""
        try:
            payload = {
                "name": "awa-hello-world",
                "input": '{"name": "World"}',
            }
            response = api_client.post("/api/v1/workflows", json=payload)

            # Should return successful status
            assert response.status_code == 200

            # Validate response structure
            response_data = response.json()
            assert isinstance(response_data, (dict, list))
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for /api/v1/workflows variant 3: {e!s}")
        except json.JSONDecodeError:
            pytest.fail(f"Invalid JSON response for /api/v1/workflows variant 3. Content: {response.text[:200]}...")

    def test_post_api_v1_workflows_missing_required_name_field(
        self,
        api_client: httpx.Client,
        api_health_check,
    ) -> None:
        """Test POST /api/v1/workflows - Missing required 'name' field."""
        try:
            invalid_payload = {
                "input": '{"name": "TestUser"}',
                "task_queue": "default-task-queue",
            }
            response = api_client.post("/api/v1/workflows", json=invalid_payload)

            # Should return error status code (422 - Validation Error)
            assert response.status_code in [400, 422, 404], (
                f"Expected error status code, got {response.status_code} for invalid payload test"
            )

            # Should return error details in JSON format
            if response.headers.get("content-type", "").startswith("application/json"):
                try:
                    error_data = response.json()
                    assert isinstance(error_data, dict), "Error response is not a JSON object"
                except json.JSONDecodeError:
                    pytest.fail(f"Invalid JSON in error response: {response.text[:200]}...")
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for invalid payload test: {e!s}")

    def test_post_api_v1_workflows_missing_required_input_field(
        self,
        api_client: httpx.Client,
        api_health_check,
    ) -> None:
        """Test POST /api/v1/workflows - Missing required 'input' field."""
        try:
            invalid_payload = {
                "name": "test-worker",
                "task_queue": "default-task-queue",
            }
            response = api_client.post("/api/v1/workflows", json=invalid_payload)

            # Should return error status code (422 - Validation Error)
            assert response.status_code in [400, 422, 404], (
                f"Expected error status code, got {response.status_code} for invalid payload test"
            )

            # Should return error details in JSON format
            if response.headers.get("content-type", "").startswith("application/json"):
                try:
                    error_data = response.json()
                    assert isinstance(error_data, dict), "Error response is not a JSON object"
                except json.JSONDecodeError:
                    pytest.fail(f"Invalid JSON in error response: {response.text[:200]}...")
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for invalid payload test: {e!s}")

    def test_post_api_v1_workflows_wrong_type_for_name_field(self, api_client: httpx.Client, api_health_check) -> None:
        """Test POST /api/v1/workflows - Wrong type for 'name' field."""
        try:
            invalid_payload = {
                "name": 12345,
                "input": '{"name": "TestUser"}',
                "task_queue": "default-task-queue",
            }
            response = api_client.post("/api/v1/workflows", json=invalid_payload)

            # Should return error status code (422 - Validation Error)
            assert response.status_code in [400, 422, 404], (
                f"Expected error status code, got {response.status_code} for invalid payload test"
            )

            # Should return error details in JSON format
            if response.headers.get("content-type", "").startswith("application/json"):
                try:
                    error_data = response.json()
                    assert isinstance(error_data, dict), "Error response is not a JSON object"
                except json.JSONDecodeError:
                    pytest.fail(f"Invalid JSON in error response: {response.text[:200]}...")
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for invalid payload test: {e!s}")

    def test_post_api_v1_workflows_wrong_type_for_input_field(self, api_client: httpx.Client, api_health_check) -> None:
        """Test POST /api/v1/workflows - Wrong type for 'input' field."""
        try:
            invalid_payload = {
                "name": "test-worker",
                "input": 12345,
                "task_queue": "default-task-queue",
            }
            response = api_client.post("/api/v1/workflows", json=invalid_payload)

            # Should return error status code (422 - Validation Error)
            assert response.status_code in [400, 422, 404], (
                f"Expected error status code, got {response.status_code} for invalid payload test"
            )

            # Should return error details in JSON format
            if response.headers.get("content-type", "").startswith("application/json"):
                try:
                    error_data = response.json()
                    assert isinstance(error_data, dict), "Error response is not a JSON object"
                except json.JSONDecodeError:
                    pytest.fail(f"Invalid JSON in error response: {response.text[:200]}...")
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for invalid payload test: {e!s}")

    def test_post_api_v1_workflows_wrong_type_for_task_queue_field(
        self,
        api_client: httpx.Client,
        api_health_check,
    ) -> None:
        """Test POST /api/v1/workflows - Wrong type for 'task_queue' field."""
        try:
            invalid_payload = {
                "name": "test-worker",
                "input": '{"name": "TestUser"}',
                "task_queue": 12345,
            }
            response = api_client.post("/api/v1/workflows", json=invalid_payload)

            # Should return error status code (422 - Validation Error)
            assert response.status_code in [400, 422, 404], (
                f"Expected error status code, got {response.status_code} for invalid payload test"
            )

            # Should return error details in JSON format
            if response.headers.get("content-type", "").startswith("application/json"):
                try:
                    error_data = response.json()
                    assert isinstance(error_data, dict), "Error response is not a JSON object"
                except json.JSONDecodeError:
                    pytest.fail(f"Invalid JSON in error response: {response.text[:200]}...")
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for invalid payload test: {e!s}")

    def test_post_api_v1_workflows_malformed_json(self, api_client: httpx.Client, api_health_check) -> None:
        """Test POST /api/v1/workflows - Malformed JSON."""
        try:
            # Send invalid JSON
            response = api_client.post(
                "/api/v1/workflows",
                content="{invalid json",
                headers={"content-type": "application/json"},
            )

            # Should return 400 or 422 for malformed data
            assert response.status_code in [400, 422], (
                f"Expected 400 or 422 status for malformed JSON, got {response.status_code}"
            )

            # Should return error details
            if response.headers.get("content-type", "").startswith("application/json"):
                try:
                    error_data = response.json()
                    assert isinstance(error_data, dict), "Error response is not a JSON object"
                except json.JSONDecodeError:
                    pytest.fail(f"Invalid JSON in error response for malformed JSON test: {response.text[:200]}...")
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for malformed JSON test: {e!s}")

    def test_post_api_v1_workflows_unsupported_content_type(self, api_client: httpx.Client, api_health_check) -> None:
        """Test POST /api/v1/workflows - Unsupported Content Type."""
        try:
            response = api_client.post(
                "/api/v1/workflows",
                content="test data",
                headers={"content-type": "text/plain"},
            )

            # Should return 415 Unsupported Media Type or 400 Bad Request
            assert response.status_code in [400, 415, 422], (
                f"Expected 400, 415, or 422 status for unsupported content type, got {response.status_code}"
            )

            # Optional: check for error response
            if response.headers.get("content-type", "").startswith("application/json"):
                try:
                    error_data = response.json()
                    assert isinstance(error_data, dict), "Error response is not a JSON object"
                except json.JSONDecodeError:
                    pass  # Some servers may not return JSON for content-type errors
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for unsupported content type test: {e!s}")

    def test_post_api_v1_workflows_schema_validation(self, api_client: httpx.Client, api_health_check) -> None:
        """Test POST /api/v1/workflows - Response Schema Validation."""
        try:
            payload = {
                "name": "test-worker",
                "input": '{"name": "TestUser"}',
                "task_queue": "default-task-queue",
            }
            response = api_client.post("/api/v1/workflows", json=payload)

            # Ensure successful response for schema validation
            assert response.status_code in [200, 201, 204], (
                f"Expected status 200/201/204, got {response.status_code} for /api/v1/workflows"
            )

            if response.status_code != 204:  # No content responses don't have body
                try:
                    response_data = response.json()
                except json.JSONDecodeError as e:
                    pytest.fail(
                        f"Invalid JSON response for /api/v1/workflows: {e!s}. Content: {response.text[:200]}...",
                    )

                # Validate response structure based on endpoint type

                # Validate no unexpected fields (if response is dict)
                if isinstance(response_data, dict):
                    # Check for common required fields based on endpoint pattern
                    # Response should not contain null values for required fields
                    def check_no_null_required_fields(obj, path=""):
                        if isinstance(obj, dict):
                            for key, value in obj.items():
                                current_path = f"{path}.{key}" if path else key
                                if value is None and key in ["status", "name", "id"]:
                                    raise AssertionError(f"Required field {current_path} is null")
                                check_no_null_required_fields(value, current_path)
                        elif isinstance(obj, list):
                            for i, item in enumerate(obj):
                                check_no_null_required_fields(item, f"{path}[{i}]")

                    check_no_null_required_fields(response_data)
        except httpx.RequestError as e:
            pytest.fail(f"Request failed for /api/v1/workflows schema validation: {e!s}")
