"""Utility module for generating consistent hashes of various data types.

This module provides the CacheUtils class which implements methods for generating
SHA-256 hashes of different data types including strings, dictionaries, lists,
Pydantic models, and generic Python objects. These hashes can be used for caching,
comparison, or other purposes requiring consistent data fingerprinting.
"""

import hashlib
import json
from typing import Any

from pydantic import BaseModel


class CacheUtils:
    @staticmethod
    def _hash_string(value: str, short: bool = False) -> str:
        """Hash a string value using SHA-256.

        Args:
            value: The string to be hashed.
            short: If True, return only the first 5 characters of the hash.
                  If False, return the full hash. Defaults to False.

        Returns:
            The hexadecimal representation of the SHA-256 hash.
            Returns empty string if input is empty or falsy.
            Returns shortened hash (5 chars) if short=True, otherwise full hash.

        """
        if not value:
            return ""
        hash_value = hashlib.sha256(value.encode()).hexdigest()
        return hash_value[:5] if short else hash_value

    @staticmethod
    def _hash_dict(value: dict, short: bool = False) -> str:
        """Hash a dictionary by converting it to a JSON string and then hashing.

        The dictionary is converted to JSON with sorted keys to ensure consistent
        hashing regardless of key insertion order.

        Args:
            value: The dictionary to be hashed.
            short: If True, return only the first 5 characters of the hash.
                  If False, return the full hash. Defaults to False.

        Returns:
            The hexadecimal representation of the SHA-256 hash of the JSON string.
            Returns shortened hash (5 chars) if short=True, otherwise full hash.

        """
        string = json.dumps(value, sort_keys=True)
        return CacheUtils._hash_string(string, short)

    @staticmethod
    def _hash_class(value: object, short: bool = False) -> str:
        """Hash a class instance by converting its variables to a JSON string and then hashing.

        The class instance's attributes are extracted using vars() and converted
        to JSON with sorted keys before hashing.

        Args:
            value: The class instance to be hashed.
            short: If True, return only the first 5 characters of the hash.
                  If False, return the full hash. Defaults to False.

        Returns:
            The hexadecimal representation of the SHA-256 hash of the JSON string
            representing the object's attributes.
            Returns shortened hash (5 chars) if short=True, otherwise full hash.

        """
        dictionary = vars(value)
        string = json.dumps(dictionary, sort_keys=True)
        return CacheUtils._hash_string(string, short)

    @staticmethod
    def _hash_pydantic(value: BaseModel, short: bool = False) -> str:
        """Hash a Pydantic model by converting it to a JSON string and then hashing.

        Uses the Pydantic model's built-in model_dump_json() method to ensure
        proper serialization of the model data.

        Args:
            value: The Pydantic model instance to be hashed.
            short: If True, return only the first 5 characters of the hash.
                  If False, return the full hash. Defaults to False.

        Returns:
            The hexadecimal representation of the SHA-256 hash of the JSON string
            generated by the Pydantic model's serialization method.
            Returns shortened hash (5 chars) if short=True, otherwise full hash.

        """
        string = value.model_dump_json()
        return CacheUtils._hash_string(string, short)

    @staticmethod
    def _get_item_json_string(item: Any) -> str:  # noqa: ANN401
        """Get the canonical JSON string representation of an item.

        For Pydantic models, uses model_dump_json() to ensure proper serialization.
        For other types, uses json.dumps with sort_keys=True for dictionaries to
        ensure consistent ordering.

        Args:
            item: The item to serialize to a JSON string. Can be a Pydantic model,
                 dictionary, list, or any JSON-serializable object.

        Returns:
            A string containing the canonical JSON representation of the item.
            For dictionaries, keys are sorted alphabetically.

        Raises:
            TypeError: If the item is not JSON serializable.

        """
        if isinstance(item, BaseModel):
            return item.model_dump_json()
        # For other types, rely on json.dumps.
        # sort_keys=True is crucial for dicts.
        return json.dumps(item, sort_keys=True)

    @staticmethod
    def _hash_list(value: list, short: bool = False) -> str:
        """Hash a list by converting it to an order-independent JSON string and then hashing.

        The order of items in the input list does not affect the resulting hash.
        Each item is converted to its canonical JSON string representation (Pydantic models
        use their specific JSON dump, dictionaries have keys sorted), and these string
        representations are then sorted before final hashing. This ensures that lists
        with the same elements produce the same hash regardless of element order.

        Args:
            value: The list to be hashed.
            short: If True, return only the first 5 characters of the hash.
                  If False, return the full hash. Defaults to False.

        Returns:
            The hexadecimal representation of the SHA-256 hash of the JSON string
            representing the sorted list elements.
            Returns shortened hash (5 chars) if short=True, otherwise full hash.

        """
        element_json_strings = [CacheUtils._get_item_json_string(i) for i in value]
        element_json_strings.sort()  # Sort the JSON string representations
        # The final string is a JSON array of these sorted JSON strings
        string = json.dumps(element_json_strings, sort_keys=True)
        return CacheUtils._hash_string(string, short)

    @staticmethod
    def hash(value: Any, short: bool = False) -> str:  # noqa: ANN401
        """Generate a hash for various types of input values.

        This method serves as a dispatcher that determines the appropriate hashing
        method based on the input type. It supports strings, Pydantic models,
        dictionaries, lists, and generic objects. The hashing is designed to be
        deterministic and consistent across runs.

        Args:
            value: The value to be hashed. Can be of type str, BaseModel (Pydantic model),
                  dict, list, or a generic object with attributes.
            short: If True, return only the first 5 characters of the hash.
                  If False, return the full hash. Defaults to False.

        Returns:
            The hexadecimal representation of the SHA-256 hash of the input value.
            Returns empty string if input is empty or falsy.
            Returns shortened hash (5 chars) if short=True, otherwise full hash.

        Raises:
            ValueError: If the input type is not supported for hashing.
            TypeError: If the value contains non-serializable objects.

        """
        if not value:
            return ""
        if isinstance(value, str):
            return CacheUtils._hash_string(value, short)
        if isinstance(value, BaseModel):
            return CacheUtils._hash_pydantic(value, short)
        if isinstance(value, dict):
            return CacheUtils._hash_dict(value, short)
        if isinstance(value, list):
            return CacheUtils._hash_list(value, short)
        if isinstance(value, object):
            return CacheUtils._hash_class(value, short)
        raise ValueError(f"Unsupported type: {type(value)}")
