#!/usr/bin/env python3
"""Dagger pipeline for publishing SDK packages to AWS CodeArtifact.

This pipeline assumes the SDK has already been generated by the Temporal workflow.
It reads the SDK configuration, packages the enabled SDKs, and publishes them to CodeArtifact.
"""

import asyncio
import logging
import os
import sys
from pathlib import Path
from typing import Any

import dagger
import yaml

from pipelines.common import setup_base_dependencies
from scripts.sdk.aws_auth_helper import configure_aws_credentials_for_dagger

# Set up logging
logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)


def configure_aws_credentials(container: dagger.Container, client: dagger.Client) -> dagger.Container:
    """Configure AWS credentials for a container using available authentication methods.

    This is a wrapper around the shared helper for backward compatibility.

    Args:
        container: The dagger container to configure
        client: The dagger client for accessing host resources

    Returns:
        The container with AWS credentials configured

    """
    return configure_aws_credentials_for_dagger(container, client)


async def read_sdk_config(src_dir: dagger.Directory, client: dagger.Client) -> dict[str, Any]:  # noqa: ARG001
    """Read and parse the SDK configuration file."""
    config_content = await src_dir.file("awa/sdk/sdk.config.yaml").contents()
    return yaml.safe_load(config_content)


async def get_sdk_version(src_dir: dagger.Directory, client: dagger.Client) -> str:  # noqa: ARG001
    """Get the SDK version from the version files generated by the Temporal workflow."""
    version_files = await src_dir.directory("sdk_dist/.hash").entries()

    # Filter for .version files
    version_files = [f for f in version_files if f.endswith(".version")]

    if not version_files:
        logger.error("No version files found. The GenerateSdkWorkflow must be run first.")
        sys.exit(1)

    # Sort to get the latest version
    version_files.sort()
    latest_version = version_files[-1].replace(".version", "")

    logger.info(f"Using SDK version: {latest_version}")
    return latest_version


async def setup_base_container(client: dagger.Client, src: dagger.Directory) -> dagger.Container:
    """Set up the base container with all required tools and dependencies."""
    # Get AWS region configuration from environment
    aws_region = os.getenv("AWS_REGION", os.getenv("AWS_DEFAULT_REGION", "us-east-1"))

    # Use the shared function to set up base dependencies
    container = setup_base_dependencies(
        client=client,
        src=src,
        python_version="3.12",
    )

    # Add AWS-specific environment variables
    container = container.with_env_variable("PYTHONUNBUFFERED", "1")
    container = container.with_env_variable("AWS_DEFAULT_REGION", aws_region)
    container = container.with_env_variable("AWS_REGION", aws_region)

    # Install pyyaml needed for SDK scripts
    container = container.with_exec(["pip", "install", "pyyaml"])

    # Install AWS CLI (architecture-aware) - needed for CodeArtifact
    container = (
        container.with_exec(
            [
                "sh",
                "-c",
                "arch=$(uname -m) && "
                'if [ "$arch" = "aarch64" ] || [ "$arch" = "arm64" ]; then '
                "  curl -sL https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip -o awscliv2.zip; "
                "else "
                "  curl -sL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip; "
                "fi",
            ],
        )
        .with_exec(["unzip", "-q", "awscliv2.zip"])
        .with_exec(["./aws/install"])
        .with_exec(["rm", "-rf", "awscliv2.zip", "aws"])
    )

    # Install .NET SDK for C# publishing
    container = (
        container.with_exec(["curl", "-fsSL", "https://dot.net/v1/dotnet-install.sh", "-o", "dotnet-install.sh"])
        .with_exec(["chmod", "+x", "dotnet-install.sh"])
        .with_exec(["./dotnet-install.sh", "--channel", "8.0", "--install-dir", "/usr/share/dotnet"])
        .with_exec(["ln", "-s", "/usr/share/dotnet/dotnet", "/usr/local/bin/dotnet"])
        .with_env_variable("DOTNET_ROOT", "/usr/share/dotnet")
        .with_env_variable("DOTNET_CLI_TELEMETRY_OPTOUT", "1")
    )

    # Mount source code
    container = container.with_mounted_directory("/app", src).with_workdir("/app")

    # Install Python dependencies with uv
    container = container.with_exec(["uv", "sync"])

    # Configure AWS credentials
    container = configure_aws_credentials(container, client)

    return container


async def check_python_version_exists(
    client: dagger.Client,
    version: str,
    package_name: str = "awa-client",
    domain: str = "slalom-all",
    domain_owner: str = "825505919920",
    repository: str = "slalom-pypi",
) -> bool:
    """Check if a Python SDK version exists in CodeArtifact."""
    logger.info(f"Checking if Python SDK {package_name} v{version} exists in CodeArtifact...")

    # Build AWS CLI command
    cmd = [
        "aws",
        "codeartifact",
        "describe-package-version",
        "--domain",
        domain,
        "--domain-owner",
        domain_owner,
        "--repository",
        repository,
        "--package",
        package_name,
        "--format",
        "pypi",
        "--package-version",
        version,
    ]

    # Set up AWS credentials
    container = client.container().from_("amazon/aws-cli:latest")
    container = configure_aws_credentials(container, client)

    # Set AWS region
    aws_region = os.getenv("AWS_REGION", os.getenv("AWS_DEFAULT_REGION", "us-east-1"))
    container = container.with_env_variable("AWS_DEFAULT_REGION", aws_region)

    # Execute command and check exit code
    try:
        exec_container = container.with_exec(cmd)
        exit_code = await exec_container.exit_code()

        if exit_code == 0:
            logger.info(f"✓ Python SDK v{version} already exists in CodeArtifact")
            return True

        # Non-zero exit code typically means package doesn't exist
        logger.info(f"✓ Python SDK v{version} does not exist (ready to publish)")
        return False
    except dagger.ExecError:
        # Command failed, likely because package doesn't exist
        logger.info(f"✓ Python SDK v{version} does not exist (ready to publish)")
        return False


async def check_csharp_version_exists(
    client: dagger.Client,
    version: str,
    package_name: str = "Awa.Client",
    domain: str = "slalom-all",
    domain_owner: str = "825505919920",
    repository: str = "slalom-nuget",
) -> bool:
    """Check if a C# SDK version exists in CodeArtifact."""
    logger.info(f"Checking if C# SDK {package_name} v{version} exists in CodeArtifact...")

    # Build AWS CLI command
    cmd = [
        "aws",
        "codeartifact",
        "describe-package-version",
        "--domain",
        domain,
        "--domain-owner",
        domain_owner,
        "--repository",
        repository,
        "--package",
        package_name,
        "--format",
        "nuget",
        "--package-version",
        version,
    ]

    # Set up AWS credentials
    container = client.container().from_("amazon/aws-cli:latest")
    container = configure_aws_credentials(container, client)

    # Set AWS region
    aws_region = os.getenv("AWS_REGION", os.getenv("AWS_DEFAULT_REGION", "us-east-1"))
    container = container.with_env_variable("AWS_DEFAULT_REGION", aws_region)

    # Execute command and check exit code
    try:
        exec_container = container.with_exec(cmd)
        exit_code = await exec_container.exit_code()

        if exit_code == 0:
            logger.info(f"✓ C# SDK v{version} already exists in CodeArtifact")
            return True

        # Non-zero exit code typically means package doesn't exist
        logger.info(f"✓ C# SDK v{version} does not exist (ready to publish)")
        return False
    except dagger.ExecError:
        # Command failed, likely because package doesn't exist
        logger.info(f"✓ C# SDK v{version} does not exist (ready to publish)")
        return False


async def setup_csharp_publishing(container: dagger.Container) -> dagger.Container:
    """Set up .NET/C# specific publishing tools."""
    # Install CodeArtifact credential provider
    container = (
        container.with_exec(["dotnet", "tool", "install", "-g", "AWS.CodeArtifact.NuGet.CredentialProvider"])
        .with_env_variable("PATH", "$PATH:/root/.dotnet/tools", expand=True)
        .with_exec(["dotnet", "codeartifact-creds", "install"])
    )

    return container


async def package_csharp_sdk(container: dagger.Container, version: str) -> dagger.Container:
    """Package the C# SDK."""
    logger.info(f"Packaging C# SDK version {version}...")

    # Only pass version, rely on script defaults for everything else
    return container.with_exec(
        [
            "uv",
            "run",
            "python",
            "scripts/sdk/package_sdk_csharp.py",
            "--version",
            version,
        ],
    )


async def publish_csharp_sdk(container: dagger.Container, version: str) -> dagger.Container:
    """Publish the C# SDK to AWS CodeArtifact."""
    logger.info(f"Publishing C# SDK version {version} to CodeArtifact...")

    # Only pass version, rely on script defaults for everything else
    cmd = [
        "uv",
        "run",
        "python",
        "scripts/sdk/publish_sdk_csharp.py",
        "--version",
        version,
        "--skip-duplicate-check",  # We've already checked in the pipeline
    ]

    # Add AWS profile if set
    aws_profile = os.getenv("AWS_PROFILE")
    if aws_profile:
        cmd.extend(["--aws-profile", aws_profile])

    return container.with_exec(cmd)


async def package_python_sdk(container: dagger.Container, version: str) -> dagger.Container:
    """Package the Python SDK."""
    logger.info(f"Packaging Python SDK version {version}...")

    # Only pass version, rely on script defaults for everything else
    return container.with_exec(
        [
            "uv",
            "run",
            "python",
            "scripts/sdk/package_sdk_python.py",
            "--version",
            version,
        ],
    )


async def check_sdks_to_publish(
    client: dagger.Client,
    enabled_languages: list[dict[str, Any]],
    version: str,
    publish_python: bool,
    publish_csharp: bool,
) -> list[tuple[str, dict[str, Any]]]:
    """Check which SDKs need to be published."""
    sdks_to_publish = []

    logger.info("\n=== Checking which SDKs need to be published ===")

    for lang in enabled_languages:
        lang_name = lang["name"]

        if lang_name == "python" and publish_python:
            # Check if Python SDK version already exists
            exists = await check_python_version_exists(client, version)
            if not exists:
                sdks_to_publish.append(("python", lang))
                logger.info(f"→ Python SDK v{version} needs to be published")
            else:
                logger.info(f"→ Python SDK v{version} already published, skipping")

        elif lang_name == "csharp" and publish_csharp:
            # Check if C# SDK version already exists
            exists = await check_csharp_version_exists(client, version)
            if not exists:
                sdks_to_publish.append(("csharp", lang))
                logger.info(f"→ C# SDK v{version} needs to be published")
            else:
                logger.info(f"→ C# SDK v{version} already published, skipping")

    return sdks_to_publish


async def publish_python_sdk(container: dagger.Container, version: str) -> dagger.Container:
    """Publish the Python SDK to AWS CodeArtifact."""
    logger.info(f"Publishing Python SDK version {version} to CodeArtifact...")

    # Only pass version, rely on script defaults for everything else
    cmd = [
        "uv",
        "run",
        "python",
        "scripts/sdk/publish_sdk_python.py",
        "--version",
        version,
        "--skip-duplicate-check",  # We've already checked in the pipeline
    ]

    # Add AWS profile if set
    aws_profile = os.getenv("AWS_PROFILE")
    if aws_profile:
        cmd.extend(["--aws-profile", aws_profile])

    return container.with_exec(cmd)


async def process_enabled_languages(
    sdk_config: dict[str, Any],
) -> list[dict[str, Any]]:
    """Process and ensure Python is included in enabled languages."""
    # Always include Python regardless of config, plus any other enabled languages
    enabled_languages = [lang for lang in sdk_config.get("languages", []) if lang.get("enabled", False)]

    # Ensure Python is always included
    python_lang = next((lang for lang in sdk_config.get("languages", []) if lang.get("name") == "python"), None)
    if python_lang and python_lang not in enabled_languages:
        enabled_languages.append(python_lang)

    return enabled_languages


async def package_and_publish_sdks(
    client: dagger.Client,
    src: dagger.Directory,
    sdks_to_publish: list[tuple[str, dict[str, Any]]],
    version: str,
) -> None:
    """Package and publish SDKs that need to be published."""
    logger.info(f"\n=== Packaging and publishing {len(sdks_to_publish)} SDK(s) ===")

    # Set up base container
    container = await setup_base_container(client, src)

    # Now package and publish only the SDKs that need it
    tasks = []

    for lang_name, _lang in sdks_to_publish:
        logger.info(f"Processing {lang_name} SDK...")

        if lang_name == "csharp":
            # Set up C# publishing environment
            csharp_container = await setup_csharp_publishing(container)

            # Package and publish C# SDK
            csharp_container = await package_csharp_sdk(csharp_container, version)
            csharp_publish_task = publish_csharp_sdk(csharp_container, version)
            tasks.append(("C#", csharp_publish_task))

        elif lang_name == "python":
            # Package and publish Python SDK
            python_container = await package_python_sdk(container, version)
            python_publish_task = publish_python_sdk(python_container, version)
            tasks.append(("Python", python_publish_task))

    # Execute all publishing tasks
    results = []
    for lang_name, task in tasks:
        logger.info(f"Publishing {lang_name} SDK...")
        task_container = await task
        exit_code = await task_container.exit_code()
        results.append((lang_name, exit_code))

        if exit_code != 0:
            # Get logs for debugging
            stdout = await task_container.stdout()
            stderr = await task_container.stderr()
            logger.error(f"{lang_name} SDK publishing failed with exit code {exit_code}")
            if stdout:
                logger.error(f"STDOUT:\n{stdout}")
            if stderr:
                logger.error(f"STDERR:\n{stderr}")

    # Check overall results
    failed = [(name, code) for name, code in results if code != 0]
    if failed:
        logger.error("\n❌ SDK Publishing Failed:")
        for name, code in failed:
            logger.error(f"  - {name}: exit code {code}")
        sys.exit(1)

    logger.info("\n✅ All enabled SDKs published successfully!")
    for name, _ in results:
        logger.info(f"  - {name} SDK v{version}")


async def main() -> None:
    """Execute the main pipeline."""
    # Allow override of what to publish
    publish_csharp = os.getenv("PUBLISH_CSHARP", "true").lower() == "true"
    publish_python = os.getenv("PUBLISH_PYTHON", "true").lower() == "true"

    async with dagger.Connection() as client:
        # Get source directory
        project_root = Path(__file__).resolve().parent.parent
        src = client.host().directory(
            str(project_root),
            exclude=[
                ".venv",
                "__pycache__",
                ".mypy_cache",
                ".pytest_cache",
                "node_modules",
                ".git",
                ".ruff_cache",
            ],
        )

        # Read SDK configuration
        sdk_config = await read_sdk_config(src, client)

        # Get SDK version from hash files
        version = await get_sdk_version(src, client)

        # Process enabled languages
        enabled_languages = await process_enabled_languages(sdk_config)
        if not enabled_languages:
            logger.info("No languages are enabled in SDK configuration")
            sys.exit(0)

        # Check which SDKs need to be published
        sdks_to_publish = await check_sdks_to_publish(
            client,
            enabled_languages,
            version,
            publish_python,
            publish_csharp,
        )

        # Exit early if nothing to publish
        if not sdks_to_publish:
            logger.info("\n✅ All SDK versions are already published. Nothing to do!")
            sys.exit(0)

        # Package and publish the SDKs
        await package_and_publish_sdks(client, src, sdks_to_publish, version)


if __name__ == "__main__":
    asyncio.run(main())
