"""Type stubs for AWA General utilities.

This file is automatically generated. Do not edit manually.
"""

from typing import Any, Optional, Dict, List, Union, Callable
from pathlib import Path

# Import only models used in function signatures
from .models import (
    WorkflowPaths,
)

def get_workflow_paths(workflow_dir: Path, workflow_info: Info) -> WorkflowPaths: ...
def get_workflow_paths_direct(workflow_dir: Path, workflow_type: str, workflow_id: str) -> WorkflowPaths: ...
