"""AWA General utilities namespace.

This file is automatically generated. Do not edit manually.
"""

from .utils.general.get_workflow_paths import get_workflow_paths as get_workflow_paths
from .utils.general.get_workflow_paths_direct import get_workflow_paths_direct as get_workflow_paths_direct

__all__ = [
    "get_workflow_paths",
    "get_workflow_paths_direct"
]
