import { defineConfig } from 'vitepress'
import { withMermaid } from "vitepress-plugin-mermaid";
import llmstxt from "vitepress-plugin-llms";

export default withMermaid(defineConfig({
  title: "[App] Docs",
  description: "TaskStream-generated Documentation for [App]",
  titleTemplate: ":title - [App]",
  outDir: "./dist",
  lastUpdated: true,
  mermaid: {
    theme: "default",
    look: "handDrawn",
    layout: "ELK", // "dagre"
    elk: {
      mergeEdges: true,
      nodePlacementStrategy: "BRANDES_KOEPF",
      cycleBreakingStrategy: "GREEDY_MODEL_ORDER",
    },
  },
  themeConfig: {
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Examples', link: '/markdown-examples' }
    ],
    sidebar: [
      {
        text: 'Examples',
        items: [
          { text: 'Markdown Examples', link: '/markdown-examples' },
          { text: 'Runtime API Examples', link: '/api-examples' }
        ]
      }
    ],
    search: {
      provider: "local",
    },
    footer: {
      message: "",
      copyright: "© Slalom, Inc. All rights reserved. Auto-generated by GenAI via TaskStream. Always verify for accuracy.",
    },
    externalLinkIcon: true,
    outline: {
      level: "deep",
      label: "Contents",
    },
  },
  markdown: {
    lineNumbers: true,
    config(md) {
      const defaultCodeInline = md.renderer.rules.code_inline!;
      md.renderer.rules.code_inline = (tokens, idx, options, env, self) => {
        tokens[idx].attrSet("v-pre", "");
        return defaultCodeInline(tokens, idx, options, env, self);
      };
    },
  },
  vite: {
    plugins: [
      llmstxt({
        ignoreFiles: [
          "introduction/release-notes/*",
          "introduction/features.md",
        ],
      }),
    ],
  },
}))
