AWA_DEFAULT_TASK_QUEUE = "awa_default"

# API Configuration
DEFAULT_AWA_API_BASE_URL = "http://localhost:8001"

# Timeouts
FILE_IO_TIMEOUT_SECONDS = 5
MCP_TIMEOUT_SECONDS = 30
BAML_TIMEOUT_SECONDS = 60 * 15
AGENT_TIMEOUT_SECONDS = 60 * 30
WORKFLOW_BUFFER_MINUTES = 5
WORKFLOW_TASK_TIMEOUT_SECONDS = 60
GIT_TIMEOUT_SECONDS = 300  # 5 minutes

# Concurrency Limits
DEFAULT_MAX_CONCURRENT_TRANSFORMS = 5
DEFAULT_MAX_CONCURRENT_AGENTS = 2

# Activity Names
AWA_PREFIX = "awa-"
AWA_ACTIVITY_READ_FILE = f"{AWA_PREFIX}read-file"
AWA_ACTIVITY_WRITE_FILE = f"{AWA_PREFIX}write-file"

# Workflow Names
AWA_WORKFLOW_TRANSFORM = f"{AWA_PREFIX}transform"

# Recipe Workflow Names
AWA_WORKFLOW_LEGACY_TO_REACT = f"{AWA_PREFIX}legacy-to-react"
AWA_WORKFLOW_AGENT_MODE_PYDANTIC_AI = f"{AWA_PREFIX}agent-mode-pydantic-ai"
AWA_WORKFLOW_OPENAI_AGENTS_SDK_DEMO = f"{AWA_PREFIX}openai-agents-sdk-demo"
AWA_WORKFLOW_JIRA_TO_PR = f"{AWA_PREFIX}jira-to-pr"

# Agent Names
AWA_AGENT_ORCHESTRATOR_PLANNING = f"{AWA_PREFIX}orchestrator-planning"
AWA_AGENT_JIRA_OPERATOR = f"{AWA_PREFIX}jira-operator"
AWA_AGENT_GIT_OPERATIONS = f"{AWA_PREFIX}git-operations"
AWA_AGENT_REPO_INITIALIZER = f"{AWA_PREFIX}repo-initializer"
AWA_AGENT_TASK_RESEARCHER = f"{AWA_PREFIX}task-researcher"
AWA_AGENT_CODE_AUTHOR = f"{AWA_PREFIX}code-author"
AWA_AGENT_CODE_REVIEWER = f"{AWA_PREFIX}code-reviewer"
AWA_AGENT_IMPLEMENTATION_VALIDATOR = f"{AWA_PREFIX}implementation-validator"
AWA_AGENT_TEST_RUNNER = f"{AWA_PREFIX}test-runner"
AWA_AGENT_BITBUCKET_OPERATOR = f"{AWA_PREFIX}bitbucket-operator"
