// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do one of these:
//
//    using Awa.Client.Models;
//
//    var buildPromptParams = BuildPromptParams.FromJson(jsonString);
//    var mcpServer = McpServer.FromJson(jsonString);
//    var isolatedAgentEnvironmentResult = IsolatedAgentEnvironmentResult.FromJson(jsonString);
//    var taskResponseModel = TaskResponseModel.FromJson(jsonString);
//    var bamlImageInputParams = BamlImageInputParams.FromJson(jsonString);
//    var readDirectoryResult = ReadDirectoryResult.FromJson(jsonString);
//    var commandResult = CommandResult.FromJson(jsonString);
//    var agentModeEnum = AgentModeEnum.FromJson(jsonString);
//    var transformParams = TransformParams.FromJson(jsonString);
//    var isolatedAgentParams = IsolatedAgentParams.FromJson(jsonString);
//    var repo = Repo.FromJson(jsonString);
//    var handoffConfig = HandoffConfig.FromJson(jsonString);
//    var jiraIssueResponse = JiraIssueResponse.FromJson(jsonString);
//    var agentToolConfig = AgentToolConfig.FromJson(jsonString);
//    var inputParams = InputParams.FromJson(jsonString);
//    var mcpServerTransport = McpServerTransport.FromJson(jsonString);
//    var handoffEvent = HandoffEvent.FromJson(jsonString);
//    var agentConfiguration = AgentConfiguration.FromJson(jsonString);
//    var transformBatchParams = TransformBatchParams.FromJson(jsonString);
//    var chunkResult = ChunkResult.FromJson(jsonString);
//    var folderInfo = FolderInfo.FromJson(jsonString);
//    var openAiAgentConfig = OpenAiAgentConfig.FromJson(jsonString);
//    var mcpTool = McpTool.FromJson(jsonString);
//    var agentProviderEnum = AgentProviderEnum.FromJson(jsonString);
//    var readFileAndParseInput = ReadFileAndParseInput.FromJson(jsonString);
//    var jiraIssueRequest = JiraIssueRequest.FromJson(jsonString);
//    var isolatedAgentEnvironmentInfo = IsolatedAgentEnvironmentInfo.FromJson(jsonString);
//    var responseFormat = ResponseFormat.FromJson(jsonString);
//    var openAiAgentResponse = OpenAiAgentResponse.FromJson(jsonString);
//    var commandInput = CommandInput.FromJson(jsonString);
//    var chunkerType = ChunkerType.FromJson(jsonString);
//    var mcpServerConfig = McpServerConfig.FromJson(jsonString);
//    var workflowPaths = WorkflowPaths.FromJson(jsonString);
//    var chunkDocumentOutput = ChunkDocumentOutput.FromJson(jsonString);
//    var chunkDocumentInput = ChunkDocumentInput.FromJson(jsonString);

namespace Awa.Client.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    /// Result of isolated agent environment operations.
    /// </summary>
    public partial class IsolatedAgentEnvironmentResult
    {
        /// <summary>
        /// Environment information if operation was successful
        /// </summary>
        [JsonProperty("environment_info")]
        public IsolatedAgentEnvironmentInfo EnvironmentInfo { get; set; }

        /// <summary>
        /// Result message or error description
        /// </summary>
        [JsonProperty("message")]
        public string Message { get; set; }

        /// <summary>
        /// Whether the operation was successful
        /// </summary>
        [JsonProperty("success")]
        public bool Success { get; set; }
    }

    /// <summary>
    /// Information about an isolated agent environment.
    /// </summary>
    public partial class IsolatedAgentEnvironmentInfo
    {
        /// <summary>
        /// Absolute path to the worktree/temporary directory. Must be an absolute path for reliable
        /// file system and git operations.
        /// </summary>
        [JsonProperty("environment_path")]
        public string EnvironmentPath { get; set; }

        /// <summary>
        /// Source branch name to merge back to (only used for Git repositories in ACT mode)
        /// </summary>
        [JsonProperty("source_branch")]
        public string SourceBranch { get; set; }

        /// <summary>
        /// Path to the source directory
        /// </summary>
        [JsonProperty("source_directory_path")]
        public string SourceDirectoryPath { get; set; }
    }

    public partial class TaskResponseModel
    {
        [JsonProperty("exception")]
        public string Exception { get; set; }

        [JsonProperty("output", NullValueHandling = NullValueHandling.Ignore)]
        public string Output { get; set; }

        [JsonProperty("reason", NullValueHandling = NullValueHandling.Ignore)]
        public string Reason { get; set; }

        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public string Status { get; set; }
    }

    public partial class ReadDirectoryResult
    {
        [JsonProperty("content")]
        public string Content { get; set; }

        [JsonProperty("file")]
        public string File { get; set; }
    }

    /// <summary>
    /// Result of executing a command.
    /// </summary>
    public partial class CommandResult
    {
        [JsonProperty("exit_code")]
        public long ExitCode { get; set; }

        [JsonProperty("output")]
        public string Output { get; set; }

        [JsonProperty("success")]
        public bool Success { get; set; }
    }

    /// <summary>
    /// Parameters for the isolated agent child workflow.
    /// </summary>
    public partial class IsolatedAgentParams
    {
        /// <summary>
        /// Agent configuration for execution
        /// </summary>
        [JsonProperty("agent_config")]
        public AgentConfiguration AgentConfig { get; set; }

        /// <summary>
        /// Timeout in minutes for agent execution. Defaults to 10 minutes.
        /// </summary>
        [JsonProperty("agent_execution_timeout_minutes", NullValueHandling = NullValueHandling.Ignore)]
        public long? AgentExecutionTimeoutMinutes { get; set; }

        /// <summary>
        /// Directory name for agent outputs in analyze mode. Defaults to 'awa-agent-output'.
        /// </summary>
        [JsonProperty("output_directory", NullValueHandling = NullValueHandling.Ignore)]
        public string OutputDirectory { get; set; }

        /// <summary>
        /// Source branch name (only used for Git repositories in ACT mode)
        /// </summary>
        [JsonProperty("source_branch", NullValueHandling = NullValueHandling.Ignore)]
        public string SourceBranch { get; set; }

        /// <summary>
        /// Source directory path (can be Git repo or regular directory)
        /// </summary>
        [JsonProperty("source_directory")]
        public string SourceDirectory { get; set; }
    }

    /// <summary>
    /// Agent configuration for execution
    /// </summary>
    public partial class AgentConfiguration
    {
        [JsonProperty("build_prompt_params", NullValueHandling = NullValueHandling.Ignore)]
        public BuildPromptParams BuildPromptParams { get; set; }

        [JsonProperty("command_file_path", NullValueHandling = NullValueHandling.Ignore)]
        public string CommandFilePath { get; set; }

        [JsonProperty("initialize", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Initialize { get; set; }

        [JsonProperty("mcp", NullValueHandling = NullValueHandling.Ignore)]
        public McpServer Mcp { get; set; }

        [JsonProperty("mode", NullValueHandling = NullValueHandling.Ignore)]
        public AgentModeEnumEnum? Mode { get; set; }

        [JsonProperty("output_schema", NullValueHandling = NullValueHandling.Ignore)]
        public string OutputSchema { get; set; }

        [JsonProperty("parent_session_id", NullValueHandling = NullValueHandling.Ignore)]
        public string ParentSessionId { get; set; }

        [JsonProperty("prompt", NullValueHandling = NullValueHandling.Ignore)]
        public string Prompt { get; set; }

        [JsonProperty("provider", NullValueHandling = NullValueHandling.Ignore)]
        public AgentProviderEnumEnum? Provider { get; set; }

        [JsonProperty("session_id", NullValueHandling = NullValueHandling.Ignore)]
        public string SessionId { get; set; }

        [JsonProperty("stream_enabled", NullValueHandling = NullValueHandling.Ignore)]
        public bool? StreamEnabled { get; set; }

        [JsonProperty("stream_session_id", NullValueHandling = NullValueHandling.Ignore)]
        public string StreamSessionId { get; set; }

        [JsonProperty("timeout_seconds", NullValueHandling = NullValueHandling.Ignore)]
        public long? TimeoutSeconds { get; set; }

        [JsonProperty("working_directory", NullValueHandling = NullValueHandling.Ignore)]
        public string WorkingDirectory { get; set; }
    }

    public partial class BuildPromptParams
    {
        [JsonProperty("inputs", NullValueHandling = NullValueHandling.Ignore)]
        public InputParams[] Inputs { get; set; }

        [JsonProperty("output_path", NullValueHandling = NullValueHandling.Ignore)]
        public string OutputPath { get; set; }

        [JsonProperty("template", NullValueHandling = NullValueHandling.Ignore)]
        public string Template { get; set; }

        [JsonProperty("template_input", NullValueHandling = NullValueHandling.Ignore)]
        public InputParams TemplateInput { get; set; }

        [JsonProperty("variables", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, object> Variables { get; set; }
    }

    /// <summary>
    /// Parameters for reading content from either a file or directory.
    /// </summary>
    public partial class InputParams
    {
        [JsonProperty("default", NullValueHandling = NullValueHandling.Ignore)]
        public string Default { get; set; }

        [JsonProperty("directory_join_str", NullValueHandling = NullValueHandling.Ignore)]
        public string DirectoryJoinStr { get; set; }

        [JsonProperty("directory_join_template_str", NullValueHandling = NullValueHandling.Ignore)]
        public string DirectoryJoinTemplateStr { get; set; }

        [JsonProperty("ignore_file_path", NullValueHandling = NullValueHandling.Ignore)]
        public string IgnoreFilePath { get; set; }

        [JsonProperty("image_mime_type", NullValueHandling = NullValueHandling.Ignore)]
        public string ImageMimeType { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("path")]
        public string Path { get; set; }
    }

    public partial class McpServer
    {
        [JsonProperty("allowed", NullValueHandling = NullValueHandling.Ignore)]
        public McpTool[] Allowed { get; set; }

        [JsonProperty("mcp_json", NullValueHandling = NullValueHandling.Ignore)]
        public string McpJson { get; set; }
    }

    public partial class McpTool
    {
        [JsonProperty("server", NullValueHandling = NullValueHandling.Ignore)]
        public string Server { get; set; }

        [JsonProperty("tools", NullValueHandling = NullValueHandling.Ignore)]
        public string[] Tools { get; set; }
    }

    public partial class Repo
    {
        [JsonProperty("branch", NullValueHandling = NullValueHandling.Ignore)]
        public string Branch { get; set; }

        [JsonProperty("path", NullValueHandling = NullValueHandling.Ignore)]
        public string Path { get; set; }
    }

    /// <summary>
    /// Configuration for agent handoffs in the OpenAI agent system.
    ///
    /// This class defines how one agent can hand off control to another agent,
    /// including tool configuration, metadata, and execution parameters.
    /// </summary>
    public partial class HandoffConfig
    {
        /// <summary>
        /// JSON Schema defining the expected structure of input data when handing off to the target
        /// agent. This schema is used to validate the data passed during handoff execution. If
        /// provided, the schema must include at least a 'type' field.
        /// </summary>
        [JsonProperty("input_type")]
        public Dictionary<string, object> InputType { get; set; }

        /// <summary>
        /// Whether this handoff configuration is enabled. Disabled handoffs will not be available as
        /// tools.
        /// </summary>
        [JsonProperty("is_enabled", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsEnabled { get; set; }

        /// <summary>
        /// Whether to remove handoff tools from the conversation history when executing the handoff.
        /// </summary>
        [JsonProperty("remove_tools_from_history", NullValueHandling = NullValueHandling.Ignore)]
        public bool? RemoveToolsFromHistory { get; set; }

        /// <summary>
        /// The target agent to hand off to. Can be an agent name (str) or an OpenAIAgentConfig
        /// instance.
        /// </summary>
        [JsonProperty("target_agent")]
        public TargetAgent TargetAgent { get; set; }

        /// <summary>
        /// Override the default tool description for this handoff. If not provided, uses the target
        /// agent's description.
        /// </summary>
        [JsonProperty("tool_description_override")]
        public string ToolDescriptionOverride { get; set; }

        /// <summary>
        /// Override the default tool name for this handoff. If not provided, uses the target agent's
        /// name.
        /// </summary>
        [JsonProperty("tool_name_override")]
        public string ToolNameOverride { get; set; }
    }

    /// <summary>
    /// Configuration for agent handoffs in the OpenAI agent system.
    ///
    /// This class defines how one agent can hand off control to another agent,
    /// including tool configuration, metadata, and execution parameters.
    ///
    /// Main configuration for OpenAI Agent execution in Temporal workflow.
    /// </summary>
    public partial class Config
    {
        /// <summary>
        /// JSON Schema defining the expected structure of input data when handing off to the target
        /// agent. This schema is used to validate the data passed during handoff execution. If
        /// provided, the schema must include at least a 'type' field.
        /// </summary>
        [JsonProperty("input_type")]
        public Dictionary<string, object> InputType { get; set; }

        /// <summary>
        /// Whether this handoff configuration is enabled. Disabled handoffs will not be available as
        /// tools.
        /// </summary>
        [JsonProperty("is_enabled", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsEnabled { get; set; }

        /// <summary>
        /// Whether to remove handoff tools from the conversation history when executing the handoff.
        /// </summary>
        [JsonProperty("remove_tools_from_history", NullValueHandling = NullValueHandling.Ignore)]
        public bool? RemoveToolsFromHistory { get; set; }

        /// <summary>
        /// The target agent to hand off to. Can be an agent name (str) or an OpenAIAgentConfig
        /// instance.
        /// </summary>
        [JsonProperty("target_agent", NullValueHandling = NullValueHandling.Ignore)]
        public TargetAgent? TargetAgent { get; set; }

        /// <summary>
        /// Override the default tool description for this handoff. If not provided, uses the target
        /// agent's description.
        /// </summary>
        [JsonProperty("tool_description_override")]
        public string ToolDescriptionOverride { get; set; }

        /// <summary>
        /// Override the default tool name for this handoff. If not provided, uses the target agent's
        /// name.
        /// </summary>
        [JsonProperty("tool_name_override")]
        public string ToolNameOverride { get; set; }

        /// <summary>
        /// List of agents to use as tools. These agents can be called as tools and return results.
        /// </summary>
        [JsonProperty("agent_tools")]
        public AgentToolElement[] AgentTools { get; set; }

        /// <summary>
        /// Description of how this agent handles handoffs or what types of handoffs it supports.
        /// </summary>
        [JsonProperty("handoff_description")]
        public string HandoffDescription { get; set; }

        /// <summary>
        /// List of possible handoff targets. Can be agent names, HandoffConfig objects, or
        /// OpenAIAgentConfig instances.
        /// </summary>
        [JsonProperty("handoffs")]
        public object[] Handoffs { get; set; }

        /// <summary>
        /// Input for the agent
        /// </summary>
        [JsonProperty("input", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(MinMaxLengthCheckConverter))]
        public string Input { get; set; }

        /// <summary>
        /// System instructions for the agent
        /// </summary>
        [JsonProperty("instructions", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(MinMaxLengthCheckConverter))]
        public string Instructions { get; set; }

        /// <summary>
        /// Maximum number of turns for the agent execution. Defaults to 10 if not specified.
        /// </summary>
        [JsonProperty("max_turns")]
        public long? MaxTurns { get; set; }

        /// <summary>
        /// List of MCP server names that match keys in the mcp.json servers object
        /// </summary>
        [JsonProperty("mcp_servers")]
        public string[] McpServers { get; set; }

        /// <summary>
        /// Additional metadata for the agent execution
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, object> Metadata { get; set; }

        /// <summary>
        /// Name of model. Must be valid default LiteLLM model name.
        /// </summary>
        [JsonProperty("model", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(MinMaxLengthCheckConverter))]
        public string Model { get; set; }

        /// <summary>
        /// Name of the agent
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(MinMaxLengthCheckConverter))]
        public string Name { get; set; }

        /// <summary>
        /// Response format: text or JSON schema
        /// </summary>
        [JsonProperty("response_format", NullValueHandling = NullValueHandling.Ignore)]
        public ResponseFormatEnum? ResponseFormat { get; set; }

        /// <summary>
        /// JSON schema for structured output (only used when response_format is JSON_SCHEMA)
        /// </summary>
        [JsonProperty("response_schema")]
        public Dictionary<string, object> ResponseSchema { get; set; }

        /// <summary>
        /// Optional workflow ID for tracking
        /// </summary>
        [JsonProperty("workflow_id")]
        public string WorkflowId { get; set; }
    }

    /// <summary>
    /// Main configuration for OpenAI Agent execution in Temporal workflow.
    ///
    /// Configuration for using an agent as a tool.
    /// </summary>
    public partial class AgentToolElement
    {
        /// <summary>
        /// List of agents to use as tools. These agents can be called as tools and return results.
        /// </summary>
        [JsonProperty("agent_tools")]
        public AgentToolElement[] AgentTools { get; set; }

        /// <summary>
        /// Description of how this agent handles handoffs or what types of handoffs it supports.
        /// </summary>
        [JsonProperty("handoff_description")]
        public string HandoffDescription { get; set; }

        /// <summary>
        /// List of possible handoff targets. Can be agent names, HandoffConfig objects, or
        /// OpenAIAgentConfig instances.
        /// </summary>
        [JsonProperty("handoffs")]
        public object[] Handoffs { get; set; }

        /// <summary>
        /// Input for the agent
        /// </summary>
        [JsonProperty("input", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(MinMaxLengthCheckConverter))]
        public string Input { get; set; }

        /// <summary>
        /// System instructions for the agent
        /// </summary>
        [JsonProperty("instructions", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(MinMaxLengthCheckConverter))]
        public string Instructions { get; set; }

        /// <summary>
        /// Maximum number of turns for the agent execution. Defaults to 10 if not specified.
        /// </summary>
        [JsonProperty("max_turns")]
        public long? MaxTurns { get; set; }

        /// <summary>
        /// List of MCP server names that match keys in the mcp.json servers object
        /// </summary>
        [JsonProperty("mcp_servers")]
        public string[] McpServers { get; set; }

        /// <summary>
        /// Additional metadata for the agent execution
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, object> Metadata { get; set; }

        /// <summary>
        /// Name of model. Must be valid default LiteLLM model name.
        /// </summary>
        [JsonProperty("model", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(MinMaxLengthCheckConverter))]
        public string Model { get; set; }

        /// <summary>
        /// Name of the agent
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(MinMaxLengthCheckConverter))]
        public string Name { get; set; }

        /// <summary>
        /// Response format: text or JSON schema
        /// </summary>
        [JsonProperty("response_format", NullValueHandling = NullValueHandling.Ignore)]
        public ResponseFormatEnum? ResponseFormat { get; set; }

        /// <summary>
        /// JSON schema for structured output (only used when response_format is JSON_SCHEMA)
        /// </summary>
        [JsonProperty("response_schema")]
        public Dictionary<string, object> ResponseSchema { get; set; }

        /// <summary>
        /// Optional workflow ID for tracking
        /// </summary>
        [JsonProperty("workflow_id")]
        public string WorkflowId { get; set; }

        /// <summary>
        /// Whether this agent tool is enabled.
        /// </summary>
        [JsonProperty("is_enabled", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsEnabled { get; set; }

        /// <summary>
        /// The agent to expose as a tool. Must be an OpenAIAgentConfig instance.
        /// </summary>
        [JsonProperty("target_agent", NullValueHandling = NullValueHandling.Ignore)]
        public OpenAiAgentConfig TargetAgent { get; set; }

        /// <summary>
        /// Override the tool description. If not provided, uses the agent's description.
        /// </summary>
        [JsonProperty("tool_description_override")]
        public string ToolDescriptionOverride { get; set; }

        /// <summary>
        /// Override the tool name. If not provided, uses the agent's name.
        /// </summary>
        [JsonProperty("tool_name_override")]
        public string ToolNameOverride { get; set; }
    }

    /// <summary>
    /// Main configuration for OpenAI Agent execution in Temporal workflow.
    ///
    /// The agent to expose as a tool. Must be an OpenAIAgentConfig instance.
    /// </summary>
    public partial class OpenAiAgentConfig
    {
        /// <summary>
        /// List of agents to use as tools. These agents can be called as tools and return results.
        /// </summary>
        [JsonProperty("agent_tools")]
        public AgentToolElement[] AgentTools { get; set; }

        /// <summary>
        /// Description of how this agent handles handoffs or what types of handoffs it supports.
        /// </summary>
        [JsonProperty("handoff_description")]
        public string HandoffDescription { get; set; }

        /// <summary>
        /// List of possible handoff targets. Can be agent names, HandoffConfig objects, or
        /// OpenAIAgentConfig instances.
        /// </summary>
        [JsonProperty("handoffs")]
        public object[] Handoffs { get; set; }

        /// <summary>
        /// Input for the agent
        /// </summary>
        [JsonProperty("input")]
        [JsonConverter(typeof(MinMaxLengthCheckConverter))]
        public string Input { get; set; }

        /// <summary>
        /// System instructions for the agent
        /// </summary>
        [JsonProperty("instructions")]
        [JsonConverter(typeof(MinMaxLengthCheckConverter))]
        public string Instructions { get; set; }

        /// <summary>
        /// Maximum number of turns for the agent execution. Defaults to 10 if not specified.
        /// </summary>
        [JsonProperty("max_turns")]
        public long? MaxTurns { get; set; }

        /// <summary>
        /// List of MCP server names that match keys in the mcp.json servers object
        /// </summary>
        [JsonProperty("mcp_servers")]
        public string[] McpServers { get; set; }

        /// <summary>
        /// Additional metadata for the agent execution
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, object> Metadata { get; set; }

        /// <summary>
        /// Name of model. Must be valid default LiteLLM model name.
        /// </summary>
        [JsonProperty("model")]
        [JsonConverter(typeof(MinMaxLengthCheckConverter))]
        public string Model { get; set; }

        /// <summary>
        /// Name of the agent
        /// </summary>
        [JsonProperty("name")]
        [JsonConverter(typeof(MinMaxLengthCheckConverter))]
        public string Name { get; set; }

        /// <summary>
        /// Response format: text or JSON schema
        /// </summary>
        [JsonProperty("response_format", NullValueHandling = NullValueHandling.Ignore)]
        public ResponseFormatEnum? ResponseFormat { get; set; }

        /// <summary>
        /// JSON schema for structured output (only used when response_format is JSON_SCHEMA)
        /// </summary>
        [JsonProperty("response_schema")]
        public Dictionary<string, object> ResponseSchema { get; set; }

        /// <summary>
        /// Optional workflow ID for tracking
        /// </summary>
        [JsonProperty("workflow_id")]
        public string WorkflowId { get; set; }
    }

    public partial class JiraIssueResponse
    {
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
        public string Description { get; set; }

        [JsonProperty("issue_type", NullValueHandling = NullValueHandling.Ignore)]
        public string IssueType { get; set; }

        [JsonProperty("key", NullValueHandling = NullValueHandling.Ignore)]
        public string Key { get; set; }

        [JsonProperty("summary", NullValueHandling = NullValueHandling.Ignore)]
        public string Summary { get; set; }
    }

    /// <summary>
    /// Configuration for using an agent as a tool.
    /// </summary>
    public partial class AgentToolConfig
    {
        /// <summary>
        /// Whether this agent tool is enabled.
        /// </summary>
        [JsonProperty("is_enabled", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsEnabled { get; set; }

        /// <summary>
        /// The agent to expose as a tool. Must be an OpenAIAgentConfig instance.
        /// </summary>
        [JsonProperty("target_agent")]
        public OpenAiAgentConfig TargetAgent { get; set; }

        /// <summary>
        /// Override the tool description. If not provided, uses the agent's description.
        /// </summary>
        [JsonProperty("tool_description_override")]
        public string ToolDescriptionOverride { get; set; }

        /// <summary>
        /// Override the tool name. If not provided, uses the agent's name.
        /// </summary>
        [JsonProperty("tool_name_override")]
        public string ToolNameOverride { get; set; }
    }

    public partial class TransformBatchParams
    {
        /// <summary>
        /// Maximum number of concurrent executions. If None or < 0, defaults to 10. If 0, unlimited.
        /// </summary>
        [JsonProperty("max_concurrency", NullValueHandling = NullValueHandling.Ignore)]
        public long? MaxConcurrency { get; set; }

        [JsonProperty("params_by_key", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, TransformParams> ParamsByKey { get; set; }

        [JsonProperty("timeout_seconds", NullValueHandling = NullValueHandling.Ignore)]
        public long? TimeoutSeconds { get; set; }
    }

    public partial class TransformParams
    {
        [JsonProperty("baml_content", NullValueHandling = NullValueHandling.Ignore)]
        public string BamlContent { get; set; }

        /// <summary>
        /// Path to a directory containing BAML files to be compiled and used for transformation
        /// </summary>
        [JsonProperty("baml_content_dir", NullValueHandling = NullValueHandling.Ignore)]
        public string BamlContentDir { get; set; }

        [JsonProperty("baml_function_name")]
        public string BamlFunctionName { get; set; }

        [JsonProperty("baml_src_dir", NullValueHandling = NullValueHandling.Ignore)]
        public string BamlSrcDir { get; set; }

        [JsonProperty("images", NullValueHandling = NullValueHandling.Ignore)]
        public BamlImageInputParams[] Images { get; set; }

        [JsonProperty("inputs", NullValueHandling = NullValueHandling.Ignore)]
        public InputParams[] Inputs { get; set; }

        [JsonProperty("model_name", NullValueHandling = NullValueHandling.Ignore)]
        public string ModelName { get; set; }

        /// <summary>
        /// JSON Path query to extract specific data from the BAML response before writing to
        /// output_path
        /// </summary>
        [JsonProperty("output_json_path", NullValueHandling = NullValueHandling.Ignore)]
        public string OutputJsonPath { get; set; }

        [JsonProperty("output_path", NullValueHandling = NullValueHandling.Ignore)]
        public string OutputPath { get; set; }

        [JsonProperty("request")]
        public object Request { get; set; }

        [JsonProperty("timeout_seconds", NullValueHandling = NullValueHandling.Ignore)]
        public long? TimeoutSeconds { get; set; }
    }

    public partial class BamlImageInputParams
    {
        [JsonProperty("base64_str")]
        public string Base64Str { get; set; }

        [JsonProperty("mime_type")]
        public string MimeType { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    /// <summary>
    /// Information about a directory and its contents.
    /// </summary>
    public partial class FolderInfo
    {
        [JsonProperty("files")]
        public string[] Files { get; set; }

        [JsonProperty("path")]
        public string Path { get; set; }

        [JsonProperty("subdirectories")]
        public string[] Subdirectories { get; set; }
    }

    /// <summary>
    /// Input model for read_file_and_parse activity.
    ///
    /// Attributes:
    /// file_path: The file path to read and parse.
    /// default_content: A string to return if the file does not exist.
    /// strict: If True, raise an exception for unsupported file types.
    /// If False (default), return raw content for unsupported types.
    /// </summary>
    public partial class ReadFileAndParseInput
    {
        /// <summary>
        /// A string to return if the file does not exist
        /// </summary>
        [JsonProperty("default_content")]
        public string DefaultContent { get; set; }

        /// <summary>
        /// The file path to read and parse
        /// </summary>
        [JsonProperty("file_path")]
        public string FilePath { get; set; }

        /// <summary>
        /// If True, raise exception for unsupported file types; if False, return raw content
        /// </summary>
        [JsonProperty("strict", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Strict { get; set; }
    }

    public partial class JiraIssueRequest
    {
        [JsonProperty("comments", NullValueHandling = NullValueHandling.Ignore)]
        public string[] Comments { get; set; }

        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
        public string Description { get; set; }

        [JsonProperty("issue_type", NullValueHandling = NullValueHandling.Ignore)]
        public string IssueType { get; set; }

        [JsonProperty("key", NullValueHandling = NullValueHandling.Ignore)]
        public string Key { get; set; }

        [JsonProperty("parent", NullValueHandling = NullValueHandling.Ignore)]
        public string Parent { get; set; }

        [JsonProperty("project_id")]
        public string ProjectId { get; set; }

        [JsonProperty("summary", NullValueHandling = NullValueHandling.Ignore)]
        public string Summary { get; set; }

        [JsonProperty("tags", NullValueHandling = NullValueHandling.Ignore)]
        public string[] Tags { get; set; }
    }

    /// <summary>
    /// Response model for OpenAI Agent execution.
    /// </summary>
    public partial class OpenAiAgentResponse
    {
        /// <summary>
        /// Name of the agent that executed
        /// </summary>
        [JsonProperty("agent_name")]
        public string AgentName { get; set; }

        /// <summary>
        /// The agent's response content
        /// </summary>
        [JsonProperty("content")]
        public string Content { get; set; }

        /// <summary>
        /// Error message if execution failed
        /// </summary>
        [JsonProperty("error")]
        public string Error { get; set; }

        /// <summary>
        /// Type of error if occurred
        /// </summary>
        [JsonProperty("error_type")]
        public string ErrorType { get; set; }

        /// <summary>
        /// Unique execution ID
        /// </summary>
        [JsonProperty("execution_id")]
        public string ExecutionId { get; set; }

        /// <summary>
        /// Total execution time
        /// </summary>
        [JsonProperty("execution_time_seconds")]
        public double ExecutionTimeSeconds { get; set; }

        /// <summary>
        /// Name of the final agent that completed the execution if handoffs occurred
        /// </summary>
        [JsonProperty("final_agent")]
        public string FinalAgent { get; set; }

        /// <summary>
        /// List of handoff events that occurred during execution
        /// </summary>
        [JsonProperty("handoff_events")]
        public HandoffEvent[] HandoffEvents { get; set; }

        /// <summary>
        /// Additional metadata from the execution
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, object> Metadata { get; set; }

        /// <summary>
        /// Model that was used
        /// </summary>
        [JsonProperty("model_used")]
        public string ModelUsed { get; set; }
    }

    /// <summary>
    /// Event representing a handoff between agents.
    /// </summary>
    public partial class HandoffEvent
    {
        /// <summary>
        /// Name of the agent handing off control
        /// </summary>
        [JsonProperty("from_agent")]
        public string FromAgent { get; set; }

        /// <summary>
        /// Data passed during the handoff
        /// </summary>
        [JsonProperty("input_data")]
        public Dictionary<string, object> InputData { get; set; }

        /// <summary>
        /// Unix timestamp when the handoff occurred
        /// </summary>
        [JsonProperty("timestamp")]
        public double Timestamp { get; set; }

        /// <summary>
        /// Name of the agent receiving control
        /// </summary>
        [JsonProperty("to_agent")]
        public string ToAgent { get; set; }

        /// <summary>
        /// Whether tools were removed from conversation history
        /// </summary>
        [JsonProperty("tools_removed", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ToolsRemoved { get; set; }
    }

    /// <summary>
    /// Input parameters for command execution.
    /// </summary>
    public partial class CommandInput
    {
        [JsonProperty("command")]
        public string Command { get; set; }

        [JsonProperty("working_dir")]
        public string WorkingDir { get; set; }
    }

    /// <summary>
    /// Configuration for MCP (Model Context Protocol) servers.
    /// </summary>
    public partial class McpServerConfig
    {
        [JsonProperty("enabled", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Enabled { get; set; }

        [JsonProperty("server_params", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, object> ServerParams { get; set; }

        [JsonProperty("transport")]
        public McpServerTransportEnum Transport { get; set; }
    }

    public partial class WorkflowPaths
    {
        [JsonProperty("agent_prompts")]
        public string AgentPrompts { get; set; }

        [JsonProperty("baml_src")]
        public string BamlSrc { get; set; }

        [JsonProperty("input")]
        public string Input { get; set; }

        [JsonProperty("output")]
        public string Output { get; set; }

        [JsonProperty("project_root")]
        public string ProjectRoot { get; set; }

        [JsonProperty("workflow_root")]
        public string WorkflowRoot { get; set; }
    }

    /// <summary>
    /// Output model for document chunking activity.
    /// </summary>
    public partial class ChunkDocumentOutput
    {
        /// <summary>
        /// The chunker type that was used
        /// </summary>
        [JsonProperty("chunker_used")]
        public string ChunkerUsed { get; set; }

        /// <summary>
        /// List of chunks with their metadata
        /// </summary>
        [JsonProperty("chunks")]
        public ChunkResult[] Chunks { get; set; }

        /// <summary>
        /// Total number of chunks created
        /// </summary>
        [JsonProperty("total_chunks")]
        public long TotalChunks { get; set; }
    }

    /// <summary>
    /// Model representing a single chunk result.
    /// </summary>
    public partial class ChunkResult
    {
        /// <summary>
        /// Ending character index in original text
        /// </summary>
        [JsonProperty("end_index")]
        public long EndIndex { get; set; }

        /// <summary>
        /// Starting character index in original text
        /// </summary>
        [JsonProperty("start_index")]
        public long StartIndex { get; set; }

        /// <summary>
        /// The text content of the chunk
        /// </summary>
        [JsonProperty("text")]
        public string Text { get; set; }

        /// <summary>
        /// Number of tokens in the chunk
        /// </summary>
        [JsonProperty("token_count")]
        public long TokenCount { get; set; }
    }

    /// <summary>
    /// Input model for document chunking activity.
    /// </summary>
    public partial class ChunkDocumentInput
    {
        /// <summary>
        /// Number of tokens to overlap between chunks
        /// </summary>
        [JsonProperty("chunk_overlap")]
        public long? ChunkOverlap { get; set; }

        /// <summary>
        /// The type of chunker to use
        /// </summary>
        [JsonProperty("chunker_type", NullValueHandling = NullValueHandling.Ignore)]
        public ChunkerTypeEnum? ChunkerType { get; set; }

        /// <summary>
        /// The text content to be chunked
        /// </summary>
        [JsonProperty("content")]
        public string Content { get; set; }

        /// <summary>
        /// Maximum size of each chunk (in tokens)
        /// </summary>
        [JsonProperty("max_chunk_size")]
        public long? MaxChunkSize { get; set; }
    }

    public enum AgentModeEnumEnum { Act, Analyze, Unknown };

    public enum AgentProviderEnumEnum { Claude, Codex, Default, Gemini, GithubCopilot, Goose, Opencode, PydanticAi, Q, Unknown };

    /// <summary>
    /// Response format: text or JSON schema
    /// </summary>
    public enum ResponseFormatEnum { JsonSchema, Text };

    public enum McpServerTransportEnum { Sse, Stdio, StreamableHttp };

    /// <summary>
    /// The type of chunker to use
    /// </summary>
    public enum ChunkerTypeEnum { Recursive, Sentence, Token };

    /// <summary>
    /// The target agent to hand off to. Can be an agent name (str) or an OpenAIAgentConfig
    /// instance.
    /// </summary>
    public partial struct TargetAgent
    {
        public OpenAiAgentConfig OpenAiAgentConfig;
        public string String;

        public static implicit operator TargetAgent(OpenAiAgentConfig OpenAiAgentConfig) => new TargetAgent { OpenAiAgentConfig = OpenAiAgentConfig };
        public static implicit operator TargetAgent(string String) => new TargetAgent { String = String };
    }

    public partial struct Handoff
    {
        public Config Config;
        public string String;

        public static implicit operator Handoff(Config Config) => new Handoff { Config = Config };
        public static implicit operator Handoff(string String) => new Handoff { String = String };
    }

    public partial class BuildPromptParams
    {
        public static BuildPromptParams FromJson(string json) => JsonConvert.DeserializeObject<BuildPromptParams>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class McpServer
    {
        public static McpServer FromJson(string json) => JsonConvert.DeserializeObject<McpServer>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class IsolatedAgentEnvironmentResult
    {
        public static IsolatedAgentEnvironmentResult FromJson(string json) => JsonConvert.DeserializeObject<IsolatedAgentEnvironmentResult>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class TaskResponseModel
    {
        public static TaskResponseModel FromJson(string json) => JsonConvert.DeserializeObject<TaskResponseModel>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class BamlImageInputParams
    {
        public static BamlImageInputParams FromJson(string json) => JsonConvert.DeserializeObject<BamlImageInputParams>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class ReadDirectoryResult
    {
        public static ReadDirectoryResult FromJson(string json) => JsonConvert.DeserializeObject<ReadDirectoryResult>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class CommandResult
    {
        public static CommandResult FromJson(string json) => JsonConvert.DeserializeObject<CommandResult>(json, Awa.Client.Models.Converter.Settings);
    }

    public class AgentModeEnum
    {
        public static AgentModeEnumEnum FromJson(string json) => JsonConvert.DeserializeObject<AgentModeEnumEnum>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class TransformParams
    {
        public static TransformParams FromJson(string json) => JsonConvert.DeserializeObject<TransformParams>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class IsolatedAgentParams
    {
        public static IsolatedAgentParams FromJson(string json) => JsonConvert.DeserializeObject<IsolatedAgentParams>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class Repo
    {
        public static Repo FromJson(string json) => JsonConvert.DeserializeObject<Repo>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class HandoffConfig
    {
        public static HandoffConfig FromJson(string json) => JsonConvert.DeserializeObject<HandoffConfig>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class JiraIssueResponse
    {
        public static JiraIssueResponse FromJson(string json) => JsonConvert.DeserializeObject<JiraIssueResponse>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class AgentToolConfig
    {
        public static AgentToolConfig FromJson(string json) => JsonConvert.DeserializeObject<AgentToolConfig>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class InputParams
    {
        public static InputParams FromJson(string json) => JsonConvert.DeserializeObject<InputParams>(json, Awa.Client.Models.Converter.Settings);
    }

    public class McpServerTransport
    {
        public static McpServerTransportEnum FromJson(string json) => JsonConvert.DeserializeObject<McpServerTransportEnum>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class HandoffEvent
    {
        public static HandoffEvent FromJson(string json) => JsonConvert.DeserializeObject<HandoffEvent>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class AgentConfiguration
    {
        public static AgentConfiguration FromJson(string json) => JsonConvert.DeserializeObject<AgentConfiguration>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class TransformBatchParams
    {
        public static TransformBatchParams FromJson(string json) => JsonConvert.DeserializeObject<TransformBatchParams>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class ChunkResult
    {
        public static ChunkResult FromJson(string json) => JsonConvert.DeserializeObject<ChunkResult>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class FolderInfo
    {
        public static FolderInfo FromJson(string json) => JsonConvert.DeserializeObject<FolderInfo>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class OpenAiAgentConfig
    {
        public static OpenAiAgentConfig FromJson(string json) => JsonConvert.DeserializeObject<OpenAiAgentConfig>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class McpTool
    {
        public static McpTool FromJson(string json) => JsonConvert.DeserializeObject<McpTool>(json, Awa.Client.Models.Converter.Settings);
    }

    public class AgentProviderEnum
    {
        public static AgentProviderEnumEnum FromJson(string json) => JsonConvert.DeserializeObject<AgentProviderEnumEnum>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class ReadFileAndParseInput
    {
        public static ReadFileAndParseInput FromJson(string json) => JsonConvert.DeserializeObject<ReadFileAndParseInput>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class JiraIssueRequest
    {
        public static JiraIssueRequest FromJson(string json) => JsonConvert.DeserializeObject<JiraIssueRequest>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class IsolatedAgentEnvironmentInfo
    {
        public static IsolatedAgentEnvironmentInfo FromJson(string json) => JsonConvert.DeserializeObject<IsolatedAgentEnvironmentInfo>(json, Awa.Client.Models.Converter.Settings);
    }

    public class ResponseFormat
    {
        public static ResponseFormatEnum FromJson(string json) => JsonConvert.DeserializeObject<ResponseFormatEnum>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class OpenAiAgentResponse
    {
        public static OpenAiAgentResponse FromJson(string json) => JsonConvert.DeserializeObject<OpenAiAgentResponse>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class CommandInput
    {
        public static CommandInput FromJson(string json) => JsonConvert.DeserializeObject<CommandInput>(json, Awa.Client.Models.Converter.Settings);
    }

    public class ChunkerType
    {
        public static ChunkerTypeEnum FromJson(string json) => JsonConvert.DeserializeObject<ChunkerTypeEnum>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class McpServerConfig
    {
        public static McpServerConfig FromJson(string json) => JsonConvert.DeserializeObject<McpServerConfig>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class WorkflowPaths
    {
        public static WorkflowPaths FromJson(string json) => JsonConvert.DeserializeObject<WorkflowPaths>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class ChunkDocumentOutput
    {
        public static ChunkDocumentOutput FromJson(string json) => JsonConvert.DeserializeObject<ChunkDocumentOutput>(json, Awa.Client.Models.Converter.Settings);
    }

    public partial class ChunkDocumentInput
    {
        public static ChunkDocumentInput FromJson(string json) => JsonConvert.DeserializeObject<ChunkDocumentInput>(json, Awa.Client.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this BuildPromptParams self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this McpServer self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this IsolatedAgentEnvironmentResult self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this TaskResponseModel self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this BamlImageInputParams self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this ReadDirectoryResult self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this CommandResult self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this AgentModeEnumEnum self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this TransformParams self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this IsolatedAgentParams self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this Repo self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this HandoffConfig self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this JiraIssueResponse self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this AgentToolConfig self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this InputParams self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this McpServerTransportEnum self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this HandoffEvent self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this AgentConfiguration self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this TransformBatchParams self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this ChunkResult self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this FolderInfo self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this OpenAiAgentConfig self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this McpTool self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this AgentProviderEnumEnum self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this ReadFileAndParseInput self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this JiraIssueRequest self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this IsolatedAgentEnvironmentInfo self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this ResponseFormatEnum self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this OpenAiAgentResponse self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this CommandInput self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this ChunkerTypeEnum self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this McpServerConfig self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this WorkflowPaths self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this ChunkDocumentOutput self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
        public static string ToJson(this ChunkDocumentInput self) => JsonConvert.SerializeObject(self, Awa.Client.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                AgentModeEnumEnumConverter.Singleton,
                AgentProviderEnumEnumConverter.Singleton,
                TargetAgentConverter.Singleton,
                HandoffConverter.Singleton,
                ResponseFormatEnumConverter.Singleton,
                McpServerTransportEnumConverter.Singleton,
                ChunkerTypeEnumConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class AgentModeEnumEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(AgentModeEnumEnum) || t == typeof(AgentModeEnumEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "act":
                    return AgentModeEnumEnum.Act;
                case "analyze":
                    return AgentModeEnumEnum.Analyze;
                case "unknown":
                    return AgentModeEnumEnum.Unknown;
            }
            throw new Exception("Cannot unmarshal type AgentModeEnumEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (AgentModeEnumEnum)untypedValue;
            switch (value)
            {
                case AgentModeEnumEnum.Act:
                    serializer.Serialize(writer, "act");
                    return;
                case AgentModeEnumEnum.Analyze:
                    serializer.Serialize(writer, "analyze");
                    return;
                case AgentModeEnumEnum.Unknown:
                    serializer.Serialize(writer, "unknown");
                    return;
            }
            throw new Exception("Cannot marshal type AgentModeEnumEnum");
        }

        public static readonly AgentModeEnumEnumConverter Singleton = new AgentModeEnumEnumConverter();
    }

    internal class AgentProviderEnumEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(AgentProviderEnumEnum) || t == typeof(AgentProviderEnumEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "claude":
                    return AgentProviderEnumEnum.Claude;
                case "codex":
                    return AgentProviderEnumEnum.Codex;
                case "default":
                    return AgentProviderEnumEnum.Default;
                case "gemini":
                    return AgentProviderEnumEnum.Gemini;
                case "github_copilot":
                    return AgentProviderEnumEnum.GithubCopilot;
                case "goose":
                    return AgentProviderEnumEnum.Goose;
                case "opencode":
                    return AgentProviderEnumEnum.Opencode;
                case "pydantic_ai":
                    return AgentProviderEnumEnum.PydanticAi;
                case "q":
                    return AgentProviderEnumEnum.Q;
                case "unknown":
                    return AgentProviderEnumEnum.Unknown;
            }
            throw new Exception("Cannot unmarshal type AgentProviderEnumEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (AgentProviderEnumEnum)untypedValue;
            switch (value)
            {
                case AgentProviderEnumEnum.Claude:
                    serializer.Serialize(writer, "claude");
                    return;
                case AgentProviderEnumEnum.Codex:
                    serializer.Serialize(writer, "codex");
                    return;
                case AgentProviderEnumEnum.Default:
                    serializer.Serialize(writer, "default");
                    return;
                case AgentProviderEnumEnum.Gemini:
                    serializer.Serialize(writer, "gemini");
                    return;
                case AgentProviderEnumEnum.GithubCopilot:
                    serializer.Serialize(writer, "github_copilot");
                    return;
                case AgentProviderEnumEnum.Goose:
                    serializer.Serialize(writer, "goose");
                    return;
                case AgentProviderEnumEnum.Opencode:
                    serializer.Serialize(writer, "opencode");
                    return;
                case AgentProviderEnumEnum.PydanticAi:
                    serializer.Serialize(writer, "pydantic_ai");
                    return;
                case AgentProviderEnumEnum.Q:
                    serializer.Serialize(writer, "q");
                    return;
                case AgentProviderEnumEnum.Unknown:
                    serializer.Serialize(writer, "unknown");
                    return;
            }
            throw new Exception("Cannot marshal type AgentProviderEnumEnum");
        }

        public static readonly AgentProviderEnumEnumConverter Singleton = new AgentProviderEnumEnumConverter();
    }

    internal class TargetAgentConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(TargetAgent) || t == typeof(TargetAgent?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.String:
                case JsonToken.Date:
                    var stringValue = serializer.Deserialize<string>(reader);
                    return new TargetAgent { String = stringValue };
                case JsonToken.StartObject:
                    var objectValue = serializer.Deserialize<OpenAiAgentConfig>(reader);
                    return new TargetAgent { OpenAiAgentConfig = objectValue };
            }
            throw new Exception("Cannot unmarshal type TargetAgent");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (TargetAgent)untypedValue;
            if (value.String != null)
            {
                serializer.Serialize(writer, value.String);
                return;
            }
            if (value.OpenAiAgentConfig != null)
            {
                serializer.Serialize(writer, value.OpenAiAgentConfig);
                return;
            }
            throw new Exception("Cannot marshal type TargetAgent");
        }

        public static readonly TargetAgentConverter Singleton = new TargetAgentConverter();
    }

    internal class HandoffConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Handoff) || t == typeof(Handoff?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.String:
                case JsonToken.Date:
                    var stringValue = serializer.Deserialize<string>(reader);
                    return new Handoff { String = stringValue };
                case JsonToken.StartObject:
                    var objectValue = serializer.Deserialize<Config>(reader);
                    return new Handoff { Config = objectValue };
            }
            throw new Exception("Cannot unmarshal type Handoff");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (Handoff)untypedValue;
            if (value.String != null)
            {
                serializer.Serialize(writer, value.String);
                return;
            }
            if (value.Config != null)
            {
                serializer.Serialize(writer, value.Config);
                return;
            }
            throw new Exception("Cannot marshal type Handoff");
        }

        public static readonly HandoffConverter Singleton = new HandoffConverter();
    }

    internal class MinMaxLengthCheckConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(string);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            var value = serializer.Deserialize<string>(reader);
            if (value.Length >= 1)
            {
                return value;
            }
            throw new Exception("Cannot unmarshal type string");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (string)untypedValue;
            if (value.Length >= 1)
            {
                serializer.Serialize(writer, value);
                return;
            }
            throw new Exception("Cannot marshal type string");
        }

        public static readonly MinMaxLengthCheckConverter Singleton = new MinMaxLengthCheckConverter();
    }

    internal class ResponseFormatEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(ResponseFormatEnum) || t == typeof(ResponseFormatEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "json_schema":
                    return ResponseFormatEnum.JsonSchema;
                case "text":
                    return ResponseFormatEnum.Text;
            }
            throw new Exception("Cannot unmarshal type ResponseFormatEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (ResponseFormatEnum)untypedValue;
            switch (value)
            {
                case ResponseFormatEnum.JsonSchema:
                    serializer.Serialize(writer, "json_schema");
                    return;
                case ResponseFormatEnum.Text:
                    serializer.Serialize(writer, "text");
                    return;
            }
            throw new Exception("Cannot marshal type ResponseFormatEnum");
        }

        public static readonly ResponseFormatEnumConverter Singleton = new ResponseFormatEnumConverter();
    }

    internal class McpServerTransportEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(McpServerTransportEnum) || t == typeof(McpServerTransportEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "sse":
                    return McpServerTransportEnum.Sse;
                case "stdio":
                    return McpServerTransportEnum.Stdio;
                case "streamable_http":
                    return McpServerTransportEnum.StreamableHttp;
            }
            throw new Exception("Cannot unmarshal type McpServerTransportEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (McpServerTransportEnum)untypedValue;
            switch (value)
            {
                case McpServerTransportEnum.Sse:
                    serializer.Serialize(writer, "sse");
                    return;
                case McpServerTransportEnum.Stdio:
                    serializer.Serialize(writer, "stdio");
                    return;
                case McpServerTransportEnum.StreamableHttp:
                    serializer.Serialize(writer, "streamable_http");
                    return;
            }
            throw new Exception("Cannot marshal type McpServerTransportEnum");
        }

        public static readonly McpServerTransportEnumConverter Singleton = new McpServerTransportEnumConverter();
    }

    internal class ChunkerTypeEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(ChunkerTypeEnum) || t == typeof(ChunkerTypeEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "recursive":
                    return ChunkerTypeEnum.Recursive;
                case "sentence":
                    return ChunkerTypeEnum.Sentence;
                case "token":
                    return ChunkerTypeEnum.Token;
            }
            throw new Exception("Cannot unmarshal type ChunkerTypeEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (ChunkerTypeEnum)untypedValue;
            switch (value)
            {
                case ChunkerTypeEnum.Recursive:
                    serializer.Serialize(writer, "recursive");
                    return;
                case ChunkerTypeEnum.Sentence:
                    serializer.Serialize(writer, "sentence");
                    return;
                case ChunkerTypeEnum.Token:
                    serializer.Serialize(writer, "token");
                    return;
            }
            throw new Exception("Cannot marshal type ChunkerTypeEnum");
        }

        public static readonly ChunkerTypeEnumConverter Singleton = new ChunkerTypeEnumConverter();
    }
}
